### PR TITLE
Removed timed exceptions that made code unclear.

### PR DESCRIPTION
**Pull request by airabinovich**
As requested, timed exceptions for firing before and after timespan were removed.
Now PetriNet.fire returns an error code specified in enum PetriNetFireOutcome.

---
This change is [Reviewable](https://reviewable.io/reviews/airabinovich/java_petri_engine/47)

### CODE REVIEW

**Comment by mauriludemann** [comment]
Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/org/unc/lac/javapetriconcurrencymonitor/monitor/PetriMonitor.java, line 464 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/47#-KYLj2uo7aHeykNjA3p7:-KYLj2uo4tcI01lyMXcO:b-2xx394) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/a4bd687fc6e5f40bf28750f8c011a8ade774880a/src/org/unc/lac/javapetriconcurrencymonitor/monitor/PetriMonitor.java#L464)):*
> fired
tried to fire

---

*[test/org/lac/javapetriconcurrencymonitor/test/cases/PetriNetTestSuite.java, line 669 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/47#-KYLlEvj6VJty_yjII-v:-KYLlEvj3TiR5I7vwBgj:b8d1jso) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/a4bd687fc6e5f40bf28750f8c011a8ade774880a/test/org/lac/javapetriconcurrencymonitor/test/cases/PetriNetTestSuite.java#L669)):*
> ```Java
> 	 * <li> And p2 has no tokens </li>
> 	 * <li> When I fire t2 </li>
> 	 * <li> Then the fire returns false </li>
> ```

The fire return PetriNetOutcome.NOT_ENABLED

---

*[test/org/lac/javapetriconcurrencymonitor/test/cases/PetriNetTestSuite.java, line 708 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/47#-KYLlkrs3owOC3h2Rn2F:-KYLlkrt1JdGOoaXDprn:bjtrmfa) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/a4bd687fc6e5f40bf28750f8c011a8ade774880a/test/org/lac/javapetriconcurrencymonitor/test/cases/PetriNetTestSuite.java#L708)):*
> ```Java
> 	 * <li> And p2 has 1 token </li>
> 	 * <li> When I fire t2 </li>
> 	 * <li> Then the fire returns true </li>
> ```

The fire return PetriNetOutcome.SUCCESS

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/47)*

**Comment by airabinovich** [comment]
Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/org/unc/lac/javapetriconcurrencymonitor/monitor/PetriMonitor.java, line 464 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/47#-KYLj2uo7aHeykNjA3p7:-KYQimjHAbEBNEcqDcPB:bqlrg5l) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/a4bd687fc6e5f40bf28750f8c011a8ade774880a/src/org/unc/lac/javapetriconcurrencymonitor/monitor/PetriMonitor.java#L464)):*
<details><summary><i>Previously, mauriludemann (Mauri) wrote…</i></summary><blockquote>

> fired
tried to fire

</blockquote></details>

I tried to write "fires". Tries to fire is ok

---

*[test/org/lac/javapetriconcurrencymonitor/test/cases/PetriNetTestSuite.java, line 669 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/47#-KYLlEvj6VJty_yjII-v:-KYQivJnACAu9zeX1o3H:b-896fix) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/a4bd687fc6e5f40bf28750f8c011a8ade774880a/test/org/lac/javapetriconcurrencymonitor/test/cases/PetriNetTestSuite.java#L669)):*
<details><summary><i>Previously, mauriludemann (Mauri) wrote…</i></summary><blockquote>

The fire return PetriNetOutcome.NOT_ENABLED
</blockquote></details>

Done.

---

*[test/org/lac/javapetriconcurrencymonitor/test/cases/PetriNetTestSuite.java, line 708 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/47#-KYLlkrs3owOC3h2Rn2F:-KYQiwVu0nt3DBBcIspl:b-896fix) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/a4bd687fc6e5f40bf28750f8c011a8ade774880a/test/org/lac/javapetriconcurrencymonitor/test/cases/PetriNetTestSuite.java#L708)):*
<details><summary><i>Previously, mauriludemann (Mauri) wrote…</i></summary><blockquote>

The fire return PetriNetOutcome.SUCCESS
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/47)*

**Comment by mauriludemann** [comment]
:lgtm:

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/47#-:-KYcvJ4JaH1wcpB0RJOi:bnfp4nl)*

**Comment by mauriludemann** [comment]
Reviewed 5 of 7 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/47)*

**Review by mauriludemann — APPROVED** [review]

**Pull request merged**
