### PR TITLE
Avoid compute enabled transitions every time it's queried...

### PR DESCRIPTION
**Pull request by airabinovich**
...in PetriNet it's a member field now.

TimedPetriNet must be initialized through startTimes.

Compute enabled transitions at initialization time is responsibility os PetriNet subclasses.
Enabled transitions are computed after firing time.

Initializing timed petri nets firing a non-timed transition is not allowed anymore

---

This change is [Reviewable](https://reviewable.io/reviews/airabinovich/java_petri_engine/28)

### CODE REVIEW

**Comment by mauriludemann** [comment]
Review status: 0 of 14 files reviewed at latest revision, 3 unresolved discussions.

---

_[src/Petri/PTPetriNet.java, line 13 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/28#-KVCQBLtjsXoGhDWU3xK:-KVCQBLtjsXoGhDWU3xL:bhpvgl5) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/a8e1333f48d34d4daa7193cd610e3d8b7e228574/src/Petri/PTPetriNet.java#L13)):_

> enabledTransitions = computeEnabledTransitions();
> should this call be here? 
> in this way the user must not initialize the petri net, because it have been initialized at the constructor. 
> Is this the expected behavior?

---

_[src/Petri/TimedPetriNet.java, line 34 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/28#-KVCZM4nI0Kgj2ZTWeF5:-KVCZM4nI0Kgj2ZTWeF6:btij4ko) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/a8e1333f48d34d4daa7193cd610e3d8b7e228574/src/Petri/TimedPetriNet.java#L34)):_

> NotInitializedTimedPetriNetException
> The exception isn't thrown here, and the new name is "NotInitializedPetriNetException"

---

_[test/unit_tests/MonitorManagerTimeTestSuite.java, line 485 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/28#-KVCaAXjMytVF-HaLNYs:-KVCaAXjMytVF-HaLNYt:b-dykxd0) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/a8e1333f48d34d4daa7193cd610e3d8b7e228574/test/unit_tests/MonitorManagerTimeTestSuite.java#L485)):_

> NotInitializedTimedPetriNetException
> should be "NotInitializedPetriNetException"

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/28)_

**Comment by airabinovich** [comment]
Review status: 0 of 14 files reviewed at latest revision, 3 unresolved discussions.

---

_[src/Petri/PTPetriNet.java, line 13 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/28#-KVCQBLtjsXoGhDWU3xK:-KVCkI4qxFS7bGRWCs4W:bj1y55d) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/a8e1333f48d34d4daa7193cd610e3d8b7e228574/src/Petri/PTPetriNet.java#L13)):_
<details><summary>

<i>Previously, mauriludemann (Mauri) wrote…</i></summary>



> > enabledTransitions = computeEnabledTransitions();
> > should this call be here? 
> > in this way the user must not initialize the petri net, because it have been initialized at the constructor. 
> > Is this the expected behavior?
> > </details>
> > see that next line sets the initializedPetriNet flag to true. Since no enabling time is needed here, it's not a problem to initialize the net at constructing time

---

_[src/Petri/TimedPetriNet.java, line 34 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/28#-KVCZM4nI0Kgj2ZTWeF5:-KVCkdbFEcWIzKFjbN48:b-67kglu) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/a8e1333f48d34d4daa7193cd610e3d8b7e228574/src/Petri/TimedPetriNet.java#L34)):_
<details><summary>

<i>Previously, mauriludemann (Mauri) wrote…</i></summary>



> > NotInitializedTimedPetriNetException
> > The exception isn't thrown here, and the new name is "NotInitializedPetriNetException"
> > </details>
> > I forgot to take it from there

---

_[test/unit_tests/MonitorManagerTimeTestSuite.java, line 485 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/28#-KVCaAXjMytVF-HaLNYs:-KVClVpt6CyRiIuF5kUq:b-896fix) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/a8e1333f48d34d4daa7193cd610e3d8b7e228574/test/unit_tests/MonitorManagerTimeTestSuite.java#L485)):_
<details><summary>

<i>Previously, mauriludemann (Mauri) wrote…</i></summary>



> > NotInitializedTimedPetriNetException
> > should be "NotInitializedPetriNetException"
> > </details>
> > Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/28)_

**Comment by mauriludemann** [comment]
Review status: 0 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/Petri/PTPetriNet.java, line 13 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/28#-KVCQBLtjsXoGhDWU3xK:-KVDmiH5iPhAkSj78d_6:blc88xs) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/a8e1333f48d34d4daa7193cd610e3d8b7e228574/src/Petri/PTPetriNet.java#L13)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> see that next line sets the initializedPetriNet flag to true. Since no enabling time is needed here, it's not a problem to initialize the net at constructing time
> </details>
> Yes, but i thought that doesn't matter the petri net type, the user always must initialize it.
> I think would be better to have an initial global condition like: "The system is initializing right now!"

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/28)_

**Comment by airabinovich** [comment]
Review status: 0 of 15 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/Petri/PTPetriNet.java, line 13 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/28#-KVCQBLtjsXoGhDWU3xK:-KVHn4FzmQZq3fFB4CcN:b-896fix) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/a8e1333f48d34d4daa7193cd610e3d8b7e228574/src/Petri/PTPetriNet.java#L13)):_
<details><summary>

<i>Previously, mauriludemann (Mauri) wrote…</i></summary>



> Yes, but i thought that doesn't matter the petri net type, the user always must initialize it.
> I think would be better to have an initial global condition like: "The system is initializing right now!"
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/28)_

**Comment by mauriludemann** [comment]
:lgtm:

---

Review status: 0 of 15 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/28#-:-KVI8yH2M5AZ0CK329xq:bnfp4nl)_

**Comment by mauriludemann** [comment]
Reviewed 9 of 15 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/28)_

**Review by mauriludemann — APPROVED** [review]

**Pull request merged**
