### PR TITLE
New exceptions FiringBeforeTimespanException and FiringAfterTimespanE…

### PR DESCRIPTION
**Pull request by airabinovich**
Move time logic from monitor into PetriNet

---
This change is [Reviewable](https://reviewable.io/reviews/airabinovich/java_petri_engine/35)

### CODE REVIEW

**Comment by airabinovich** [comment]
Review status: 0 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

_[src/org/unc/lac/javapetriconcurrencymonitor/petrinets/PetriNet.java, line 185 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/35#-KWFqH-GclebCGPFF54q:-KWFqH-GclebCGPFF54r:b-1qcufw) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/dba338bc6528cef0653da0856a60ecd476453c1b/src/org/unc/lac/javapetriconcurrencymonitor/petrinets/PetriNet.java#L185)):_

> , long fireTime

PetriNet should not know about time, that's only for TimedPetriNet

---

_[src/org/unc/lac/javapetriconcurrencymonitor/petrinets/PetriNet.java, line 203 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/35#-KWFqAGMcuL3N2UR561U:-KWFqAGMcuL3N2UR561V:bb8pq9t) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/dba338bc6528cef0653da0856a60ecd476453c1b/src/org/unc/lac/javapetriconcurrencymonitor/petrinets/PetriNet.java#L203)):_

> // time checks
> 
> ```
>   if(transition.isTimed()){
>       if(transition.isBeforeTimeSpan(fireTime)){
>           throw new FiringBeforeTimespanException();
>       }
>       else if(!transition.insideTimeSpan(fireTime)){
>           throw new FiringAfterTimespanException();
>       }
> ```

these should be in TimedPetriNet

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/35)_

**Comment by mauriludemann** [comment]
Review status: 0 of 13 files reviewed at latest revision, 7 unresolved discussions.

---

_[src/org/unc/lac/javapetriconcurrencymonitor/petrinets/PetriNet.java, line 133 at r2](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/35#-KWUfLekHVKTTcT_JfA9:-KWUfLelQcQhiQQVJ_qW:b-29t1s) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/c51a78afe14aa696126e1824c7cc1e83629a86fd/src/org/unc/lac/javapetriconcurrencymonitor/petrinets/PetriNet.java#L133)):_

> ``` Java
>    * Fires the transition whose index is given as argument if it's enabled and updates current marking.
>    * @param transitionIndex Transition's index to be fired.
>    * @param fireTime The timestamp of the firing moment in the format given by {@link System#currentTimeMillis()}
> ```

This parameter doesn't exist in the method

---

_[src/org/unc/lac/javapetriconcurrencymonitor/petrinets/PetriNet.java, line 151 at r2](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/35#-KWUfue1hi0NEon_JPUu:-KWUfue1hi0NEon_JPUv:bsydoc7) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/c51a78afe14aa696126e1824c7cc1e83629a86fd/src/org/unc/lac/javapetriconcurrencymonitor/petrinets/PetriNet.java#L151)):_

> if the net hasn't been initialized before calling this method
> this example throws a NotInitializedPetriNetException, so i think you can put another example for the PetriNetException use

---

_[src/org/unc/lac/javapetriconcurrencymonitor/petrinets/TimedPetriNet.java, line 39 at r2](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/35#-KWUgXud6Esftd03qX1w:-KWUgXud6Esftd03qX1x:bnj7hl0) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/c51a78afe14aa696126e1824c7cc1e83629a86fd/src/org/unc/lac/javapetriconcurrencymonitor/petrinets/TimedPetriNet.java#L39)):_

> ``` Java
>    * @return True if the fire was successful
>    * @throws IllegalArgumentException If the index is negative or greater than the last transition index.
>    * @throws PetriNetException If an error regarding the petri occurs, for instance if the net hasn't been initialized before calling this method.
> ```

same as above

---

_[src/org/unc/lac/javapetriconcurrencymonitor/petrinets/TimedPetriNet.java, line 59 at r2](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/35#-KWUgjgPxdd8qCAHqJGD:-KWUgjgPxdd8qCAHqJGE:bb7od0r) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/c51a78afe14aa696126e1824c7cc1e83629a86fd/src/org/unc/lac/javapetriconcurrencymonitor/petrinets/TimedPetriNet.java#L59)):_

> ``` Java
>    * @param t The transition to be fired
>    * @return True if the fire was successful
>    * @throws PetriNetException If an error regarding the petri occurs, for instance if the net hasn't been initialized before calling this method.
> ```

same

---

_[src/org/unc/lac/javapetriconcurrencymonitor/petrinets/TimedPetriNet.java, line 62 at r2](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/35#-KWUgzWetStWa2QSlqu0:-KWUgzWetStWa2QSlqu1:b-wap1cu) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/c51a78afe14aa696126e1824c7cc1e83629a86fd/src/org/unc/lac/javapetriconcurrencymonitor/petrinets/TimedPetriNet.java#L62)):_

> ``` Java
>    * @throws IllegalArgumentException If the given transition is null or its index doesn't match any existing transition
>    * @see TimedPetriNet#initializePetriNet()
>    * @see PetriNet#fire(Transition, long)
> ```

same question about the parameter "long"

---

_[src/org/unc/lac/javapetriconcurrencymonitor/petrinets/components/Transition.java, line 120 at r2](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/35#-KWUioG0BCb0_qvrPXef:-KWUioG0BCb0_qvrPXeg:b-y7b7ra) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/c51a78afe14aa696126e1824c7cc1e83629a86fd/src/org/unc/lac/javapetriconcurrencymonitor/petrinets/components/Transition.java#L120)):_

> inside the this ..
> Maybe you can change that

---

_[src/org/unc/lac/javapetriconcurrencymonitor/petrinets/components/Transition.java, line 134 at r2](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/35#-KWUj9xim8K488VagIf8:-KWUj9xim8K488VagIf9:bnj7hl0) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/c51a78afe14aa696126e1824c7cc1e83629a86fd/src/org/unc/lac/javapetriconcurrencymonitor/petrinets/components/Transition.java#L134)):_

> ``` Java
> 
>   /**
>    * Tests whether timestamp is before the this transition's span for timed transitions.
> ```

same as above

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/35)_

**Comment by airabinovich** [comment]
Review status: 0 of 13 files reviewed at latest revision, 7 unresolved discussions.

---

_[src/org/unc/lac/javapetriconcurrencymonitor/petrinets/PetriNet.java, line 133 at r2](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/35#-KWUfLekHVKTTcT_JfA9:-KWUrNOazDRqu3IRn-cN:b7xqa1d) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/c51a78afe14aa696126e1824c7cc1e83629a86fd/src/org/unc/lac/javapetriconcurrencymonitor/petrinets/PetriNet.java#L133)):_
<details><summary>

<i>Previously, mauriludemann (Mauri) wrote…</i></summary>



> This parameter doesn't exist in the method
> </details>
> I forgot to delete it, it was there in the previous patch

---

_[src/org/unc/lac/javapetriconcurrencymonitor/petrinets/PetriNet.java, line 151 at r2](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/35#-KWUfue1hi0NEon_JPUu:-KWUrXnb5bEOmBeoGGzE:b-dbyqjb) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/c51a78afe14aa696126e1824c7cc1e83629a86fd/src/org/unc/lac/javapetriconcurrencymonitor/petrinets/PetriNet.java#L151)):_
<details><summary>

<i>Previously, mauriludemann (Mauri) wrote…</i></summary>



> > if the net hasn't been initialized before calling this method
> > this example throws a NotInitializedPetriNetException, so i think you can put another example for the PetriNetException use
> > </details>
> > PetriNetException is abstract so it won't ever be thrown.
> > This is just an abstration to comply with Liskov substitution principle and so be able to add new exceptions used by subclasses but supported by the parent class

---

_[src/org/unc/lac/javapetriconcurrencymonitor/petrinets/TimedPetriNet.java, line 39 at r2](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/35#-KWUgXud6Esftd03qX1w:-KWUscwsnyKYEwINm6Xy:b-a92grr) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/c51a78afe14aa696126e1824c7cc1e83629a86fd/src/org/unc/lac/javapetriconcurrencymonitor/petrinets/TimedPetriNet.java#L39)):_
<details><summary>

<i>Previously, mauriludemann (Mauri) wrote…</i></summary>



> same as above
> </details>
> Look at method description, these are the other possibilities added by this method override

---

_[src/org/unc/lac/javapetriconcurrencymonitor/petrinets/TimedPetriNet.java, line 59 at r2](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/35#-KWUgjgPxdd8qCAHqJGD:-KWUstgmSQcBCK8qjWc2:bubfnsk) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/c51a78afe14aa696126e1824c7cc1e83629a86fd/src/org/unc/lac/javapetriconcurrencymonitor/petrinets/TimedPetriNet.java#L59)):_
<details><summary>

<i>Previously, mauriludemann (Mauri) wrote…</i></summary>



> same
> </details>
> answer in previous comment

---

_[src/org/unc/lac/javapetriconcurrencymonitor/petrinets/TimedPetriNet.java, line 62 at r2](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/35#-KWUgzWetStWa2QSlqu0:-KWUswIFtvkH1kKrmyzy:b6fuiti) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/c51a78afe14aa696126e1824c7cc1e83629a86fd/src/org/unc/lac/javapetriconcurrencymonitor/petrinets/TimedPetriNet.java#L62)):_
<details><summary>

<i>Previously, mauriludemann (Mauri) wrote…</i></summary>



> same question about the parameter "long"
> </details>
> I'll fix this

---

_[src/org/unc/lac/javapetriconcurrencymonitor/petrinets/components/Transition.java, line 120 at r2](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/35#-KWUioG0BCb0_qvrPXef:-KWUt0Q51qY1VR7uYSpW:b32wtd) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/c51a78afe14aa696126e1824c7cc1e83629a86fd/src/org/unc/lac/javapetriconcurrencymonitor/petrinets/components/Transition.java#L120)):_
<details><summary>

<i>Previously, mauriludemann (Mauri) wrote…</i></summary>



> > inside the this ..
> > Maybe you can change that
> > </details>
> > ok

---

_[src/org/unc/lac/javapetriconcurrencymonitor/petrinets/components/Transition.java, line 134 at r2](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/35#-KWUj9xim8K488VagIf8:-KWUt1pmZDy-mphDVU0F:b32wtd) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/c51a78afe14aa696126e1824c7cc1e83629a86fd/src/org/unc/lac/javapetriconcurrencymonitor/petrinets/components/Transition.java#L134)):_
<details><summary>

<i>Previously, mauriludemann (Mauri) wrote…</i></summary>



> same as above
> </details>
> ok

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/35)_

**Comment by mauriludemann** [comment]
:lgtm:

---

Reviewed 3 of 10 files at r1, 7 of 9 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/35#-:-KWUwQ2UEoCWGnnVhc-x:bnfp4nl)_

**Review by mauriludemann — APPROVED** [review]

**Pull request merged**
