### PR TITLE
Subscribe by name, issue #38

### PR DESCRIPTION
**Pull request by airabinovich**
This change is [Reviewable](https://reviewable.io/reviews/airabinovich/java_petri_engine/39)

### CODE REVIEW

**Comment by airabinovich** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

_[test/org/lac/javapetriconcurrencymonitor/test/cases/PetriMonitorTestSuite.java, line 1044 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/39#-KWjqYde5nTtXkJS8uY6:-KWjqYde5nTtXkJS8uY7:bxy086r) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/ee75a002cc76df82d69b6f8a6258c84e51eeaf7c/test/org/lac/javapetriconcurrencymonitor/test/cases/PetriMonitorTestSuite.java#L1044)):_

> ``` Java
>       TransitionEventObserver obs = new TransitionEventObserver();
>       try{
>           monitor.subscribeToTransition("fake_name", obs);
> ```

add Assert.fail("exception should've been thrown before this point");

---

_[test/org/lac/javapetriconcurrencymonitor/test/cases/PetriMonitorTestSuite.java, line 1060 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/39#-KWjqeyF3Qf1k4GlhJSz:-KWjqeyF3Qf1k4GlhJT-:bxy086r) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/ee75a002cc76df82d69b6f8a6258c84e51eeaf7c/test/org/lac/javapetriconcurrencymonitor/test/cases/PetriMonitorTestSuite.java#L1060)):_

> ``` Java
>       TransitionEventObserver obs = new TransitionEventObserver();
>       try{
>           monitor.subscribeToTransition((String)null, obs);
> ```

add Assert.fail("exception should've been thrown before this point");

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/39)_

**Comment by juanjoarce7456** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/org/unc/lac/javapetriconcurrencymonitor/monitor/PetriMonitor.java, line 226 at r2](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/39#-KWorUH3BP6_3aGHsDvW:-KWorUH3BP6_3aGHsDvX:b-79fhs1) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/1df5ebbfedc972f4c835b065b07352cb4d3ef1a1/src/org/unc/lac/javapetriconcurrencymonitor/monitor/PetriMonitor.java#L226)):_

> if(_transitionName == null){
>           throw new IllegalArgumentException("Null string given as transition name");
>       }
> 
> ```
>   Optional<Transition> transition = Arrays.stream(petri.getTransitions())
>           .filter((Transition t) -> t.getName().equals(_transitionName))
>           .findFirst();
> 
>   if(!transition.isPresent()){
>       throw new IllegalArgumentException("There is no transition matching name " + _transitionName);
>   }
> ```

Maybe you should create a getTransitionByName method on PetriNet class to avoid repeating this piece of code on fireTransition(final String transitionName, boolean perennialFire).

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/39)_

**Comment by mauriludemann** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

_[src/org/unc/lac/javapetriconcurrencymonitor/petrinets/PetriNet.java, line 232 at r3](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/39#-KWrLHRGEB7hhlcG0L-I:-KWrLHRGEB7hhlcG0L-J:b-ciy5g5) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/1aea730b7c3e118207cbd28375a59751d1752546/src/org/unc/lac/javapetriconcurrencymonitor/petrinets/PetriNet.java#L232)):_

> ``` Java
>    * @throws IllegalArgumentException if transitionName doesn't match any transition
>    */
>   public Transition getTransition(final String transitionName) throws IllegalArgumentException{
> ```

getTransition and getPlace have the same code, if they are both PetriNodes, maybe we can do only one method "getNode".

---

_[test/org/lac/javapetriconcurrencymonitor/test/cases/PetriMonitorTestSuite.java, line 1034 at r3](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/39#-KWrMYqVoxaW1slwWkZa:-KWrMYqWf26v3lLfQWCt:b-wxh229) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/1aea730b7c3e118207cbd28375a59751d1752546/test/org/lac/javapetriconcurrencymonitor/test/cases/PetriMonitorTestSuite.java#L1034)):_

> is
> I don't like this "is"

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/39)_

**Comment by airabinovich** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

_[src/org/unc/lac/javapetriconcurrencymonitor/monitor/PetriMonitor.java, line 226 at r2](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/39#-KWorUH3BP6_3aGHsDvW:-KWrPaM1E_RtszUEOOBU:b-uet0vu) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/1df5ebbfedc972f4c835b065b07352cb4d3ef1a1/src/org/unc/lac/javapetriconcurrencymonitor/monitor/PetriMonitor.java#L226)):_
<details><summary>

<i>Previously, juanjoarce7456 (Juan Jose Arce Giacobbe) wrote…</i></summary>



> > if(_transitionName == null){
> >             throw new IllegalArgumentException("Null string given as transition name");
> >         }
> > 
> > ```
> >     Optional<Transition> transition = Arrays.stream(petri.getTransitions())
> >             .filter((Transition t) -> t.getName().equals(_transitionName))
> >             .findFirst();
> > 
> >     if(!transition.isPresent()){
> >         throw new IllegalArgumentException("There is no transition matching name " + _transitionName);
> >     }
> > ```
> 
> Maybe you should create a getTransitionByName method on PetriNet class to avoid repeating this piece of code on fireTransition(final String transitionName, boolean perennialFire).
> </details>
> Done.
> I'll change this anyway to unify this method and getPlaceByName from another patch

---

_[src/org/unc/lac/javapetriconcurrencymonitor/petrinets/PetriNet.java, line 232 at r3](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/39#-KWrLHRGEB7hhlcG0L-I:-KWrOg7sj93Lb15mQaoN:bhvcogg) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/1aea730b7c3e118207cbd28375a59751d1752546/src/org/unc/lac/javapetriconcurrencymonitor/petrinets/PetriNet.java#L232)):_
<details><summary>

<i>Previously, mauriludemann (Mauri) wrote…</i></summary>



> getTransition and getPlace have the same code, if they are both PetriNodes, maybe we can do only one method "getNode".
> </details>
> Ok, and let's do it as a template

---

_[test/org/lac/javapetriconcurrencymonitor/test/cases/PetriMonitorTestSuite.java, line 1034 at r3](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/39#-KWrMYqVoxaW1slwWkZa:-KWrPSg86OblOfLqX5rJ:b-7ykxjm) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/1aea730b7c3e118207cbd28375a59751d1752546/test/org/lac/javapetriconcurrencymonitor/test/cases/PetriMonitorTestSuite.java#L1034)):_
<details><summary>

<i>Previously, mauriludemann (Mauri) wrote…</i></summary>



> > is
> > I don't like this "is"
> > </details>
> > check your grammar and you'll like it

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/39)_

**Comment by mauriludemann** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/39#-:-KX8TzmtdWcxFcIrdyz6:bnfp4nl)*

**Review by mauriludemann — APPROVED** [review]

**Comment by juanjoarce7456** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/39#-:-KX8i7swcrGux24aaIc8:bnfp4nl)*

**Pull request merged**
