### PR TITLE
improve README.md as user manual

### PR DESCRIPTION
**Pull request by airabinovich**
This change is [Reviewable](https://reviewable.io/reviews/airabinovich/java_petri_engine/40)

### CODE REVIEW

**Comment by mauriludemann** [comment]
Review status: 0 of 2 files reviewed at latest revision, 8 unresolved discussions.

---

*[README.md, line 63 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/40#-KXGTix_LAcBnp4qhkz2:-KXGTixaRJgLottq2c5w:bfh4qbf) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/46664ef6f2d8a0d54f409941e5e4f8400a3285ea/README.md#L63)):*
> ```Markdown
>     - Are case sensitive
> 
> All values are optional for labels but to specify any value, all values to its left must be specified.  
> ```

Not clear

---

*[README.md, line 65 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/40#-KXGTknpszST1c5JCS9C:-KXGTknpszST1c5JCS9D:bp7p9cw) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/46664ef6f2d8a0d54f409941e5e4f8400a3285ea/README.md#L65)):*
> ```Markdown
> All values are optional for labels but to specify any value, all values to its left must be specified.  
> The default values are:
> - automatic_value: A
> ```

the default value is not A

---

*[README.md, line 74 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/40#-KXGVTJn6_ioIDLaizDJ:-KXGVTJn6_ioIDLaizDK:b7o2bvr) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/46664ef6f2d8a0d54f409941e5e4f8400a3285ea/README.md#L74)):*
> ```Markdown
> This label specifies that the associated transition is __Fired__, __Informed__, and has a guard called __foobar__ which enables the transition by __false__ value
> 
> ### Setting Up my Petri Net and Monitor
> ```

Is necessary to say that this software DOESN'T check the correct Petri structure?  (i.e. deadlock)

---

*[README.md, line 82 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/40#-KXGW7s7E3Z5cqWOkVDB:-KXGW7s7E3Z5cqWOkVDC:bgvdofd) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/46664ef6f2d8a0d54f409941e5e4f8400a3285ea/README.md#L82)):*
> (TimedPetriNet)
remove it

---

*[README.md, line 110 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/40#-KXGW_UXWIAk-yK8htTC:-KXGW_UXWIAk-yK8htTD:b-9lz7ib) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/46664ef6f2d8a0d54f409941e5e4f8400a3285ea/README.md#L110)):*
> idex
index

---

*[README.md, line 153 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/40#-KXGXiVjNi5a3d-MnMkR:-KXGXiVjNi5a3d-MnMkS:bak569o) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/46664ef6f2d8a0d54f409941e5e4f8400a3285ea/README.md#L153)):*
> to signal another thread that some task has started or finished.
this another thread was waiting a condition, or the mutual exclusion

---

*[README.md, line 230 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/40#-KXGZ98yNGvNP8ESA-VV:-KXGZ98yNGvNP8ESA-VW:bd4z0go) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/46664ef6f2d8a0d54f409941e5e4f8400a3285ea/README.md#L230)):*
> now
not

---

*[README.md, line 231 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/40#-KXG_KK0PYahbw5VSaUn:-KXG_KK0PYahbw5VSaUo:bbiljen) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/46664ef6f2d8a0d54f409941e5e4f8400a3285ea/README.md#L231)):*
> Firing an automatic transition
I think, it would be better put something like: "A thread firing explicitly an automatic transition..."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/40)*

**Comment by juanjoarce7456** [comment]
Review status: 0 of 2 files reviewed at latest revision, 9 unresolved discussions.

---

*[README.md, line 4 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/40#-KXHTDM-dhyx904huEnq:-KXHTDM-dhyx904huEnr:b-nk6fni) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/46664ef6f2d8a0d54f409941e5e4f8400a3285ea/README.md#L4)):*
> typo: defined 

---

*[README.md, line 65 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/40#-KXGTknpszST1c5JCS9C:-KXHUu2MI7qTPYB-_VCr:b-z5ywb7) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/46664ef6f2d8a0d54f409941e5e4f8400a3285ea/README.md#L65)):*
<details><summary><i>Previously, mauriludemann (Mauri) wrote…</i></summary>
> the default value is not A
</details>
By default isAutomatic value on PnmlParser is false.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/40)*

**Comment by mauriludemann** [comment]
Review status: 0 of 2 files reviewed at latest revision, 9 unresolved discussions.

---

*[README.md, line 230 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/40#-KXGZ98yNGvNP8ESA-VV:-KXHZGtIhjBoYTa-G5tS:b-w55coo) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/46664ef6f2d8a0d54f409941e5e4f8400a3285ea/README.md#L230)):*
> If firing a transition was now successfull
was not

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/40)*

**Comment by airabinovich** [comment]
Review status: 0 of 2 files reviewed at latest revision, 9 unresolved discussions.

---

*[README.md, line 4 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/40#-KXHTDM-dhyx904huEnq:-KweK-tfwx7bGzszWiqE:b-896fix) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/46664ef6f2d8a0d54f409941e5e4f8400a3285ea/README.md#L4)):*
<details><summary><i>Previously, juanjoarce7456 (Juan Jose Arce Giacobbe) wrote…</i></summary><blockquote>

> typo: defined 
</blockquote></details>

Done.

---

*[README.md, line 63 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/40#-KXGTix_LAcBnp4qhkz2:-KweK1vTWJ__5SkMjdaJ:b-896fix) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/46664ef6f2d8a0d54f409941e5e4f8400a3285ea/README.md#L63)):*
<details><summary><i>Previously, mauriludemann (Mauri) wrote…</i></summary><blockquote>

Not clear
</blockquote></details>

Done.

---

*[README.md, line 65 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/40#-KXGTknpszST1c5JCS9C:-KweK3p_HVI4JbQkCWcg:b-896fix) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/46664ef6f2d8a0d54f409941e5e4f8400a3285ea/README.md#L65)):*
<details><summary><i>Previously, juanjoarce7456 (Juan Jose Arce Giacobbe) wrote…</i></summary><blockquote>

By default isAutomatic value on PnmlParser is false.
</blockquote></details>

Done.

---

*[README.md, line 74 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/40#-KXGVTJn6_ioIDLaizDJ:-KweK7L6g-A2PrdfDXpV:bx959gw) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/46664ef6f2d8a0d54f409941e5e4f8400a3285ea/README.md#L74)):*
<details><summary><i>Previously, mauriludemann (Mauri) wrote…</i></summary><blockquote>

Is necessary to say that this software DOESN'T check the correct Petri structure?  (i.e. deadlock)
</blockquote></details>

No, we never say we do anything to the model itself but executing it

---

*[README.md, line 82 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/40#-KXGW7s7E3Z5cqWOkVDB:-KweKFfUkkvLVo8VngQC:b-896fix) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/46664ef6f2d8a0d54f409941e5e4f8400a3285ea/README.md#L82)):*
<details><summary><i>Previously, mauriludemann (Mauri) wrote…</i></summary><blockquote>

> (TimedPetriNet)
remove it
</blockquote></details>

Done.

---

*[README.md, line 110 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/40#-KXGW_UXWIAk-yK8htTC:-KweKIqGJLGo-aHCDQiu:b-896fix) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/46664ef6f2d8a0d54f409941e5e4f8400a3285ea/README.md#L110)):*
<details><summary><i>Previously, mauriludemann (Mauri) wrote…</i></summary><blockquote>

> idex
index
</blockquote></details>

Done.

---

*[README.md, line 153 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/40#-KXGXiVjNi5a3d-MnMkR:-KweKYvXamDJ2b2ceQM7:bcpweb9) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/46664ef6f2d8a0d54f409941e5e4f8400a3285ea/README.md#L153)):*
<details><summary><i>Previously, mauriludemann (Mauri) wrote…</i></summary><blockquote>

> to signal another thread that some task has started or finished.
this another thread was waiting a condition, or the mutual exclusion
</blockquote></details>

It's a concurrency monitor, I think that's understood

---

*[README.md, line 230 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/40#-KXGZ98yNGvNP8ESA-VV:-KweKe2E1HLK64DZsMJx:b-896fix) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/46664ef6f2d8a0d54f409941e5e4f8400a3285ea/README.md#L230)):*
<details><summary><i>Previously, mauriludemann (Mauri) wrote…</i></summary><blockquote>

> If firing a transition was now successfull
was not
</blockquote></details>

Done.

---

*[README.md, line 231 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/40#-KXG_KK0PYahbw5VSaUn:-KweKga9kVNeHLaBeFwl:b1gx6az) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/46664ef6f2d8a0d54f409941e5e4f8400a3285ea/README.md#L231)):*
<details><summary><i>Previously, mauriludemann (Mauri) wrote…</i></summary><blockquote>

> Firing an automatic transition
I think, it would be better put something like: "A thread firing explicitly an automatic transition..."
</blockquote></details>

Maybe but I didn't think it was too important. It's just a __don't do it__

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/40)*

**Comment by juanjoarce7456** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/40)*

**Comment by mauriludemann** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/40#-:-KwjSgf0Jxu5j_udVM65:bnfp4nl)*

**Comment by mauriludemann** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/40)*

**Pull request merged**
