### PR TITLE
javadoc and code style tweaks

### PR DESCRIPTION
**Pull request by airabinovich**
This change is [Reviewable](https://reviewable.io/reviews/airabinovich/java_petri_engine/61)

### CODE REVIEW

**Comment by juanjoarce7456** [comment]
:lgtm:

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/61#-:-KyagYJwfV3gZz9on7RQ:bnfp4nl)*

**Comment by juanjoarce7456** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/61)*

**Comment by juanjoarce7456** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/61#-:-KzAwNEVx35MKI0b4nZt:bnfp4nl)*

**Comment by airabinovich** [comment]
Reviewed 12 of 12 files at r1, 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/61)*

**Pull request merged**
