### PR TITLE
Added support for perennial firing

### PR DESCRIPTION
**Pull request by airabinovich**
Also added some tests for perennial fire in timed and not timed transitions using both monitor and petri fire interfaces.

TODO: before merge, solve comments on issue #5

---

This change is [Reviewable](https://reviewable.io/reviews/airabinovich/java_petri_engine/18)

### CODE REVIEW

**Comment by juanjoarce7456** [comment]
Reviewed 2 of 10 files at r1.
Review status: 2 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

_[src/monitor_petri/MonitorManager.java, line 78 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/18#-KTqWGqSeUne0W6Ru8nH:-KTqWGqSeUne0W6Ru8nI:bduqb0y) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/3af181388862068d3be38a483ed7bc76a57df66b/src/monitor_petri/MonitorManager.java#L78)):_

> ``` Java
>    * For timed transitions, the calling thread sleeps until the transition reaches its time span, only then fires it.
>    * @param transitionToFire The transition to fire
>    * @param perenialFire True indicates a perennial fire
> ```

This param is not used in this version of the fire method

---

_[src/monitor_petri/MonitorManager.java, line 304 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/18#-KTqZ89m4LMb4Cf9cMvI:-KTqZ89m4LMb4Cf9cMvJ:b5iaydr) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/3af181388862068d3be38a483ed7bc76a57df66b/src/monitor_petri/MonitorManager.java#L304)):_

> ``` Java
>                   }
>                   else if(!perennialFire) {
>                       //The calling thread came late, the time is over. Thus the thread releases the input mutex and goes to sleep
> ```

Doubt: Why don't you destroy the thread instead of sleeping it forever? Wouldn't it help to save memory resources?

---

_[src/Petri/PetriNet.java, line 124 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/18#-KTqfF35y6vZ7b7ZhhJI:-KTqfF35y6vZ7b7ZhhJJ:b-xje6v6) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/3af181388862068d3be38a483ed7bc76a57df66b/src/Petri/PetriNet.java#L124)):_

> ``` Java
>    * @return true if t was fired. For a perennial fire, returns true in any case.
>    */
>   public boolean fire(Transition t, boolean perennialFire) {
> ```

Is this firing method being used?

---

_[src/Petri/TimedPetriNet.java, line 26 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/18#-KTqfPoskUdiR9uycyyR:-KTqfPotIvLElZxjHcFe:b36aixk) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/3af181388862068d3be38a483ed7bc76a57df66b/src/Petri/TimedPetriNet.java#L26)):_

> ``` Java
>   }
> 
>   public boolean fire(int transitionIndex, boolean perennialFire){
> ```

Same as before

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/18)_

**Comment by airabinovich** [comment]
Review status: 2 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

_[src/monitor_petri/MonitorManager.java, line 78 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/18#-KTqWGqSeUne0W6Ru8nH:-KTqmIzzgeRktd-6uzGQ:b-896fix) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/3af181388862068d3be38a483ed7bc76a57df66b/src/monitor_petri/MonitorManager.java#L78)):_
<details><summary>

<i>Previously, juanjoarce7456 wrote…</i></summary>



> This param is not used in this version of the fire method
> </details>
> Done.

---

_[src/monitor_petri/MonitorManager.java, line 304 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/18#-KTqZ89m4LMb4Cf9cMvI:-KTqmNR-N5i72HwHrx_F:b-fvp8r3) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/3af181388862068d3be38a483ed7bc76a57df66b/src/monitor_petri/MonitorManager.java#L304)):_
<details><summary>

<i>Previously, juanjoarce7456 wrote…</i></summary>



> Doubt: Why don't you destroy the thread instead of sleeping it forever? Wouldn't it help to save memory resources?
> </details>
> This doesn't need  be forever. Is the transition gets enabled, another thread might wake it up

---

_[src/Petri/PetriNet.java, line 124 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/18#-KTqfF35y6vZ7b7ZhhJI:-KTqmcnC2BysgyED7AOW:b-r3h9ob) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/3af181388862068d3be38a483ed7bc76a57df66b/src/Petri/PetriNet.java#L124)):_
<details><summary>

<i>Previously, juanjoarce7456 wrote…</i></summary>



> Is this firing method being used?
> </details>
> This if a public method, it's a part of the interface. It might be used by a future extension

---

_[src/Petri/TimedPetriNet.java, line 26 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/18#-KTqfPoskUdiR9uycyyR:-KTqmo7et0kxaPsVvXMD:bnj7hl0) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/3af181388862068d3be38a483ed7bc76a57df66b/src/Petri/TimedPetriNet.java#L26)):_
<details><summary>

<i>Previously, juanjoarce7456 wrote…</i></summary>



> Same as before
> </details>
> same as above

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/18)_

**Comment by juanjoarce7456** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/Petri/PetriNet.java, line 126 at r2](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/18#-KTztpL1YFcPRVJYZTBj:-KTztpL1YFcPRVJYZTBk:b-2x300v) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/0a136b5fb31a7946e8fba45620eb2e59d1207519/src/Petri/PetriNet.java#L126)):_

> ``` Java
>    * @param transitionIndex Transition's index to be fired.
>    * @return true if transitionIndex was fired. For a perennial fire, returns true in any case.
>    * @throws IllegalArgumentException If transitionIndex is negative of grater than the last transition index.
> ```

Typo: "of grater"

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/18)_

**Comment by mauriludemann** [comment]
_[src/Petri/PetriNet.java, line 141 at r2](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/18#-KU-a1sJ9Wzi4obaWeQW:-KU-a1sJ9Wzi4obaWeQX:bcahnjo) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/0a136b5fb31a7946e8fba45620eb2e59d1207519/src/Petri/PetriNet.java#L141)):_

> ``` Java
>       }       
>       for(int i = 0; i < currentMarking.length; i++){
>           if(resetMatrix[i][transitionIndex]){
> ```

Maybe could be:
currentMarking[i] = (resetMatrix[i][transitionIndex]) ? 0 : currentMarking[i] + inc[i][transitionIndex];

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/18)_

**Comment by airabinovich** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

_[src/Petri/PetriNet.java, line 141 at r2](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/18#-KU-a1sJ9Wzi4obaWeQW:-KU-bJG-DuC2DXHDwY4O:b-zbvcs1) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/0a136b5fb31a7946e8fba45620eb2e59d1207519/src/Petri/PetriNet.java#L141)):_
<details><summary>

<i>Previously, mauriludemann wrote…</i></summary>



> Maybe could be:
> currentMarking[i] = (resetMatrix[i][transitionIndex]) ? 0 : currentMarking[i] + inc[i][transitionIndex];
> </details>
> Not a big difference, I don't think a new patch is needed just for that

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/18)_

**Comment by mauriludemann** [comment]
_[src/Petri/PetriNet.java, line 141 at r2](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/18#-KU-a1sJ9Wzi4obaWeQW:-KU-cAmgJEKzyw9fq-xD:bug1s2j) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/0a136b5fb31a7946e8fba45620eb2e59d1207519/src/Petri/PetriNet.java#L141)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> Not a big difference, I don't think a new patch is needed just for that
> </details>
> Was just a suggestion

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/18)_

**Comment by mauriludemann** [comment]
_[test/unit_tests/MonitorManagerTestSuite.java, line 738 at r2](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/18#-KU-bgbvZtx1SRlK8L0z:-KU-bgbvZtx1SRlK8L1-:b-rl4879) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/0a136b5fb31a7946e8fba45620eb2e59d1207519/test/unit_tests/MonitorManagerTestSuite.java#L738)):_

> ``` Java
> 
>   /**
>    * <li> Given t1 is disabled </li>
> ```

what are the connections between t1, p0 and p1?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/18)_

**Comment by mauriludemann** [comment]
Reviewed 6 of 10 files at r1, 3 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/18)_

**Comment by airabinovich** [comment]
Review status: 7 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

_[src/Petri/PetriNet.java, line 126 at r2](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/18#-KTztpL1YFcPRVJYZTBj:-KU024yMR_bgVvbmOKH0:b-896fix) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/0a136b5fb31a7946e8fba45620eb2e59d1207519/src/Petri/PetriNet.java#L126)):_
<details><summary>

<i>Previously, juanjoarce7456 wrote…</i></summary>



> Typo: "of grater"
> </details>
> Done.

---

_[src/Petri/PetriNet.java, line 141 at r2](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/18#-KU-a1sJ9Wzi4obaWeQW:-KU035o6lo6LctO0rSwH:b-68ohfg) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/0a136b5fb31a7946e8fba45620eb2e59d1207519/src/Petri/PetriNet.java#L141)):_
<details><summary>

<i>Previously, mauriludemann wrote…</i></summary>



> Was just a suggestion
> </details>
> On a second thought, even if what you say is right, it'd make the function harder to understand for someone who doesn't know the code that well and there's no big gain anyway

---

_[test/unit_tests/MonitorManagerTestSuite.java, line 738 at r2](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/18#-KU-bgbvZtx1SRlK8L0z:-KU02IQKixxJ6dtqQNHU:b-896fix) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/0a136b5fb31a7946e8fba45620eb2e59d1207519/test/unit_tests/MonitorManagerTestSuite.java#L738)):_
<details><summary>

<i>Previously, mauriludemann wrote…</i></summary>



> what are the connections between t1, p0 and p1?
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/18)_

**Comment by mauriludemann** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/18)_

**Comment by juanjoarce7456** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

_[src/Petri/PetriNet.java, line 126 at r2](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/18#-KTztpL1YFcPRVJYZTBj:-KU07G7a9FqfKJ1r6sAb:b-efgu4b) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/0a136b5fb31a7946e8fba45620eb2e59d1207519/src/Petri/PetriNet.java#L126)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> Done.
> </details>
> Stills containing the typo in "grater"

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/18)_

**Comment by juanjoarce7456** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[src/Petri/PetriNet.java, line 141 at r2](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/18#-KU-a1sJ9Wzi4obaWeQW:-KU081REy02ditL29ILr:bhm0tw) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/0a136b5fb31a7946e8fba45620eb2e59d1207519/src/Petri/PetriNet.java#L141)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> On a second thought, even if what you say is right, it'd make the function harder to understand for someone who doesn't know the code that well and there's no big gain anyway
> </details>
> Fight fight fight!

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/18)_

**Comment by airabinovich** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[src/Petri/PetriNet.java, line 126 at r2](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/18#-KTztpL1YFcPRVJYZTBj:-KU0AwxwEduT5grupzXH:bo32kdp) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/0a136b5fb31a7946e8fba45620eb2e59d1207519/src/Petri/PetriNet.java#L126)):_
<details><summary>

<i>Previously, juanjoarce7456 wrote…</i></summary>



> Stills containing the typo in "grater"
> </details>
> didn't notice. I'll fix it next time i'll  modify this file

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/18)_

**Comment by mauriludemann** [comment]
_[src/Petri/PetriNet.java, line 126 at r2](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/18#-KTztpL1YFcPRVJYZTBj:-KU0BdfXTpwdFOEPoeE3:b-ljt7lc) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/0a136b5fb31a7946e8fba45620eb2e59d1207519/src/Petri/PetriNet.java#L126)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> didn't notice. I'll fix it next time i'll  modify this file
> </details>
> Fight x3 !!

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/18)_

**Comment by juanjoarce7456** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/18#-:-KU0D0jHJex9wDjRkCOJ:bnfp4nl)_

**Pull request merged**
