### PR TITLE
Add reset arcs

### PR DESCRIPTION
**Pull request by mauriludemann**
Implementation of reset arcs with their respective tests.

---

This change is [Reviewable](https://reviewable.io/reviews/airabinovich/java_petri_engine/11)

### CODE REVIEW

**Comment by airabinovich** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

_[src/Petri/Arc.java, line 18 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/11#-KTJpAf-NcKZXr596ujN:-KTJpAf031tdZC0seiAZ:buvhasz) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/ce2628ed8ad394043422fe61b2335a9cada57524/src/Petri/Arc.java#L18)):_

> It has no weight
> Actually, the arc has weight but it's not fixed. It depends on the source place marking

---

_[src/Petri/PetriNet.java, line 121 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/11#-KTJr897CN3e4Htgint-:-KTJr897CN3e4Htgint0:b9hurfu) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/ce2628ed8ad394043422fe61b2335a9cada57524/src/Petri/PetriNet.java#L121)):_

> // m_(i+1) = m_i + I*d
>       // when d is a vector where every element is 0 but the nth which is 1
>       // it's equivalent to pick nth column from Incidence matrix (I) 

This comments needs an update

---

_[src/Petri/PetriNet.java, line 246 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/11#-KTJrGVsFC1BPDjgzpz5:-KTJrGVt-JoI9gVwucmg:b-xiznvr) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/ce2628ed8ad394043422fe61b2335a9cada57524/src/Petri/PetriNet.java#L246)):_

> this.isMatrixNonZero(inhibitionMatrix)

this call is too expensive to make it everytime and it's return value is constant for a constant petri net.

This should be replace by a field, private boolean isPetriNetInhibited and filled at startup time

---

_[src/Petri/PetriNet.java, line 255 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/11#-KTJraSTdtw4Ob-1S3ya:-KTJraSTdtw4Ob-1S3yb:bz0v777) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/ce2628ed8ad394043422fe61b2335a9cada57524/src/Petri/PetriNet.java#L255)):_

> this.isMatrixNonZero(resetMatrix)

same here, isPetriNetResetted

---

_[src/Petri/PetriNetFactory.java, line 159 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/11#-KTJsVLVa56XHeWJjr2N:-KTJsVLWrPRksdaplFIR:bukaskq) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/ce2628ed8ad394043422fe61b2335a9cada57524/src/Petri/PetriNetFactory.java#L159)):_

> ``` Java
>               }
>           }
> 
> ```

Maybe we could add a verification here. If resetMatrix[i][j] > 0 && ( inhibitionMatrix[i][j] > 0 || preIncidence[i][j] > 0) throw an error

---

_[test/unit_tests/PetriNetTestSuite.java, line 435 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/11#-KTJt_MH6AImo7LuKN6Z:-KTJt_MH6AImo7LuKN6_:b-d1yos0) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/ce2628ed8ad394043422fe61b2335a9cada57524/test/unit_tests/PetriNetTestSuite.java#L435)):_

>  Given p0, p1 and p2 have one token

Is this used in the test? If not, remove it

---

_[test/unit_tests/PetriNetTestSuite.java, line 443 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/11#-KTJtkvNNa8SJadctuB9:-KTJtkvOsln_Gg1gYORY:b-kkhlsb) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/ce2628ed8ad394043422fe61b2335a9cada57524/test/unit_tests/PetriNetTestSuite.java#L443)):_

> And a token is put into p4

add a pre-condition to the test explaining t3 feeds p4

---

_[test/unit_tests/PetriNetTestSuite.java, line 469 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/11#-KTJuZAu5YVNeDEqmcAC:-KTJuZAu5YVNeDEqmcAD:bfjtph) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/ce2628ed8ad394043422fe61b2335a9cada57524/test/unit_tests/PetriNetTestSuite.java#L469)):_

> Given p0, p1 and p2 have one token

same here, not used, remove

---

_[test/unit_tests/PetriNetTestSuite.java, line 470 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/11#-KTJueJnBEYxu2n3kye1:-KTJueJnBEYxu2n3kye2:b-4y9h9e) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/ce2628ed8ad394043422fe61b2335a9cada57524/test/unit_tests/PetriNetTestSuite.java#L470)):_

> and p4

p4 is not a part of this test

---

_[test/unit_tests/PetriNetTestSuite.java, line 478 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/11#-KTJuity3u1L9SC9vnHC:-KTJuitzNXUVbO6M_vvP:byi01tv) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/ce2628ed8ad394043422fe61b2335a9cada57524/test/unit_tests/PetriNetTestSuite.java#L478)):_

> ``` Java
>    */
>   @Test
>   public void FireTransitionWithResetArcShouldNotBeEnabledWhenSourcePlaceHasNoMarking(){
> ```

There is no need to use another petri for this case... you can use the same but add another reset arc from a place which has no tokens by default

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/11)_

**Comment by mauriludemann** [comment]
_[src/Petri/Arc.java, line 18 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/11#-KTJpAf-NcKZXr596ujN:-KTK9HLZrivaup2Qq3qW:blqbi67) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/ce2628ed8ad394043422fe61b2335a9cada57524/src/Petri/Arc.java#L18)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> > It has no weight
> > Actually, the arc has weight but it's not fixed. It depends on the source place marking
> 
> </details>
> The arc has no weight, just empties the source place, because doesn't matter the "weight" or "marking" when the transition is fired.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/11)_

**Comment by mauriludemann** [comment]
_[test/unit_tests/PetriNetTestSuite.java, line 470 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/11#-KTJueJnBEYxu2n3kye1:-KTKDYB9pWheoas3E5UU:be69gfs) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/ce2628ed8ad394043422fe61b2335a9cada57524/test/unit_tests/PetriNetTestSuite.java#L470)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> > and p4
> 
> p4 is not a part of this test
> </details>
> Yes, it is. We have to verify if p4 is empty after fire t3

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/11)_

**Comment by mauriludemann** [comment]
_[test/unit_tests/PetriNetTestSuite.java, line 469 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/11#-KTJuZAu5YVNeDEqmcAC:-KTKEaSjxdBc_n_0r-pK:b-896fix) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/ce2628ed8ad394043422fe61b2335a9cada57524/test/unit_tests/PetriNetTestSuite.java#L469)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> > Given p0, p1 and p2 have one token
> 
> same here, not used, remove
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/11)_

**Comment by mauriludemann** [comment]
_[test/unit_tests/PetriNetTestSuite.java, line 443 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/11#-KTJtkvNNa8SJadctuB9:-KTKEiHnFJFDZto6S0Xu:b-896fix) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/ce2628ed8ad394043422fe61b2335a9cada57524/test/unit_tests/PetriNetTestSuite.java#L443)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> > And a token is put into p4
> 
> add a pre-condition to the test explaining t3 feeds p4
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/11)_

**Comment by mauriludemann** [comment]
_[test/unit_tests/PetriNetTestSuite.java, line 435 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/11#-KTJt_MH6AImo7LuKN6Z:-KTKEl0YFcPAvbrFMp4T:b-896fix) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/ce2628ed8ad394043422fe61b2335a9cada57524/test/unit_tests/PetriNetTestSuite.java#L435)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> >  Given p0, p1 and p2 have one token
> 
> Is this used in the test? If not, remove it
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/11)_

**Comment by mauriludemann** [comment]
_[src/Petri/PetriNet.java, line 255 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/11#-KTJraSTdtw4Ob-1S3ya:-KTKEniSGfG6ALLq56Sb:b-896fix) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/ce2628ed8ad394043422fe61b2335a9cada57524/src/Petri/PetriNet.java#L255)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> > this.isMatrixNonZero(resetMatrix)
> 
> same here, isPetriNetResetted
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/11)_

**Comment by mauriludemann** [comment]
_[src/Petri/PetriNet.java, line 246 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/11#-KTJrGVsFC1BPDjgzpz5:-KTKEq4i3U0BJ_r4anZa:b-896fix) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/ce2628ed8ad394043422fe61b2335a9cada57524/src/Petri/PetriNet.java#L246)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> > this.isMatrixNonZero(inhibitionMatrix)
> 
> this call is too expensive to make it everytime and it's return value is constant for a constant petri net.
> 
> This should be replace by a field, private boolean isPetriNetInhibited and filled at startup time
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/11)_

**Comment by mauriludemann** [comment]
_[src/Petri/PetriNet.java, line 121 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/11#-KTJr897CN3e4Htgint-:-KTKFgAFPdKm47rjxXpL:b-896fix) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/ce2628ed8ad394043422fe61b2335a9cada57524/src/Petri/PetriNet.java#L121)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> > // m_(i+1) = m_i + I*d
> >         // when d is a vector where every element is 0 but the nth which is 1
> >         // it's equivalent to pick nth column from Incidence matrix (I) 
> 
> This comments needs an update
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/11)_

**Comment by airabinovich** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[src/Petri/Arc.java, line 18 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/11#-KTJpAf-NcKZXr596ujN:-KTKH0lMEzb59ujXX1SE:b-ra1ivq) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/ce2628ed8ad394043422fe61b2335a9cada57524/src/Petri/Arc.java#L18)):_
<details><summary>

<i>Previously, mauriludemann wrote…</i></summary>



> The arc has no weight, just empties the source place, because doesn't matter the "weight" or "marking" when the transition is fired.
> </details>
> As I said, the arc has weight but it's not fixed, it's not a constant

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/11)_

**Comment by mauriludemann** [comment]
_[src/Petri/PetriNetFactory.java, line 159 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/11#-KTJsVLVa56XHeWJjr2N:-KTKIF2zQKDPPnl_xpRZ:b-896fix) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/ce2628ed8ad394043422fe61b2335a9cada57524/src/Petri/PetriNetFactory.java#L159)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> Maybe we could add a verification here. If resetMatrix[i][j] > 0 && ( inhibitionMatrix[i][j] > 0 || preIncidence[i][j] > 0) throw an error
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/11)_

**Comment by airabinovich** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_[src/Petri/PetriNet.java, line 255 at r2](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/11#-KTKL5sR11eVlpNUaqnP:-KTKL5sSYkYIDKBbntZL:bmofvke) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/bbb471466e2cdfff23490a77407d4159a7943d41/src/Petri/PetriNet.java#L255)):_

> isInhibitionMatrixZero

this'd be a lot more readable if this field was named something like "petriNetHasInhibitors"

---

_[src/Petri/PetriNet.java, line 264 at r2](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/11#-KTKLXnOi4zM3v6CJ17B:-KTKLXnP3I3JeO_-egGb:bt6xv6r) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/bbb471466e2cdfff23490a77407d4159a7943d41/src/Petri/PetriNet.java#L264)):_

> isResetMatrixZero

same here

---

_[src/Petri/PetriNetFactory.java, line 164 at r2](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/11#-KTKLqb0ToLn1HdqQzuq:-KTKLqb0ToLn1HdqQzur:b-4xed06) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/bbb471466e2cdfff23490a77407d4159a7943d41/src/Petri/PetriNetFactory.java#L164)):_

> If you have a transition with reset arc, you cannot add other entry arc
> this comment needs some fix

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/11)_

**Comment by mauriludemann** [comment]
_[src/Petri/PetriNetFactory.java, line 164 at r2](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/11#-KTKLqb0ToLn1HdqQzuq:-KTKN46igCyAsAEGfom1:b3vfy7j) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/bbb471466e2cdfff23490a77407d4159a7943d41/src/Petri/PetriNetFactory.java#L164)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> > If you have a transition with reset arc, you cannot add other entry arc
> > this comment needs some fix
> > </details>
> > "Cannot have other entry arcs in the same transition when there is a reset arc." ?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/11)_

**Comment by mauriludemann** [comment]
_[src/Petri/PetriNet.java, line 255 at r2](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/11#-KTKL5sR11eVlpNUaqnP:-KTKNglNNs4VBPIySMM5:bfwv65i) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/bbb471466e2cdfff23490a77407d4159a7943d41/src/Petri/PetriNet.java#L255)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> > isInhibitionMatrixZero
> 
> this'd be a lot more readable if this field was named something like "petriNetHasInhibitors"
> </details>
> Yes, but with this implementation, the inhibition matrix always exists, so the name asks if is zero or not

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/11)_

**Comment by mauriludemann** [comment]
_[src/Petri/PetriNet.java, line 264 at r2](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/11#-KTKLXnOi4zM3v6CJ17B:-KTKOBqR57hZXSNMhIEj:bb7od0r) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/bbb471466e2cdfff23490a77407d4159a7943d41/src/Petri/PetriNet.java#L264)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> > isResetMatrixZero
> 
> same here
> </details>
> same

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/11)_

**Comment by mauriludemann** [comment]
_[src/Petri/PetriNet.java, line 255 at r2](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/11#-KTKL5sR11eVlpNUaqnP:-KTM7sZA8-z2EgCQfW5X:b-896fix) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/bbb471466e2cdfff23490a77407d4159a7943d41/src/Petri/PetriNet.java#L255)):_
<details><summary>

<i>Previously, mauriludemann wrote…</i></summary>



> Yes, but with this implementation, the inhibition matrix always exists, so the name asks if is zero or not
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/11)_

**Comment by mauriludemann** [comment]
_[src/Petri/PetriNet.java, line 264 at r2](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/11#-KTKLXnOi4zM3v6CJ17B:-KTM7vfvFgyNmhZV7OqQ:b-896fix) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/bbb471466e2cdfff23490a77407d4159a7943d41/src/Petri/PetriNet.java#L264)):_
<details><summary>

<i>Previously, mauriludemann wrote…</i></summary>



> same
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/11)_

**Comment by mauriludemann** [comment]
_[src/Petri/PetriNetFactory.java, line 164 at r2](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/11#-KTKLqb0ToLn1HdqQzuq:-KTM809FRjRb6mftURTC:b-896fix) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/bbb471466e2cdfff23490a77407d4159a7943d41/src/Petri/PetriNetFactory.java#L164)):_
<details><summary>

<i>Previously, mauriludemann wrote…</i></summary>



> "Cannot have other entry arcs in the same transition when there is a reset arc." ?
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/11)_

**Comment by mauriludemann** [comment]
_[src/Petri/PetriNetFactory.java, line 159 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/11#-KTJsVLVa56XHeWJjr2N:-KTM81ktmqaeMC9INKjO:b-896fix) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/ce2628ed8ad394043422fe61b2335a9cada57524/src/Petri/PetriNetFactory.java#L159)):_
<details><summary>

<i>Previously, mauriludemann wrote…</i></summary>



> Done.
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/11)_

**Comment by mauriludemann** [comment]
Review status: 7 of 10 files reviewed at latest revision, 5 unresolved discussions.

---

_[test/unit_tests/PetriNetTestSuite.java, line 478 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/11#-KTJuity3u1L9SC9vnHC:-KTM6hr67J61GJ6FnX3X:bb6un1j) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/ce2628ed8ad394043422fe61b2335a9cada57524/test/unit_tests/PetriNetTestSuite.java#L478)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> There is no need to use another petri for this case... you can use the same but add another reset arc from a place which has no tokens by default
> </details>
> Done

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/11)_

**Comment by airabinovich** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/11#-:-KTM8UzrLAyOX8GHTc22:bnfp4nl)_

**Review by airabinovich — APPROVED** [review]

**Pull request merged**
