### PR TITLE
Thread sleeping for a transition before its time span will now sleep in PetriMonitor class

### PR DESCRIPTION
**Pull request by airabinovich**
Removed every thread management logic from TimeSpan.

---
This change is [Reviewable](https://reviewable.io/reviews/airabinovich/java_petri_engine/32)

### CODE REVIEW

**Comment by mauriludemann** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

_[src/org/unc/lac/javapetriconcurrencymonitor/monitor/PetriMonitor.java, line 75 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/32#-KW5nWnlAvWxMkSfe62E:-KW5nWnmtJyhzyM8r5dL:b-rguri8) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/f525cef93f05803b74e125a34bbe9354fc80d40a/src/org/unc/lac/javapetriconcurrencymonitor/monitor/PetriMonitor.java#L75)):_

> ``` Java
>       jsonMapper = new ObjectMapper();
> 
>       anyThreadSleepingforTransition = new AtomicBoolean[transitionsAmount];
> ```

Only question:
This line don't create an AtomicBoolean array? why are you filling that array again with AtomicBooleans?

---

_[src/org/unc/lac/javapetriconcurrencymonitor/monitor/PetriMonitor.java, line 357 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/32#-KW5oBr1VH0B0Bj-5vIJ:-KW5oBr1VH0B0Bj-5vIK:b-d8h2le) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/f525cef93f05803b74e125a34bbe9354fc80d40a/src/org/unc/lac/javapetriconcurrencymonitor/monitor/PetriMonitor.java#L357)):_

> ``` Java
>                   if(transitionSpan.isBeforeTimeSpan(fireAttemptTime) && anyThreadSleepingforTransition[transitionIndex].compareAndSet(false, true)){
>                       // The calling thread came before time span, and there is nobody sleeping waiting for this transition,
>                       // release the input mutex and sleep here until the time has come.
> ```

"releases" - "sleeps"

---

_[src/org/unc/lac/javapetriconcurrencymonitor/monitor/PetriMonitor.java, line 360 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/32#-KW5p1fZm_M5cTkoT4yr:-KW5p1fZm_M5cTkoT4ys:b59o2v9) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/f525cef93f05803b74e125a34bbe9354fc80d40a/src/org/unc/lac/javapetriconcurrencymonitor/monitor/PetriMonitor.java#L360)):_

> ``` Java
>                       inQueue.unlock();
> 
>                       long enablingTime = transitionSpan.getEnableTime() + transitionSpan.getTimeBegin();
> ```

This part must move to PetriNet like Orlando said, i think it would be better to do that in other branch.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/32)_

**Comment by mauriludemann** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/32)_

**Comment by mauriludemann** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/32#-:-KW5pZKL26vFYCCtpxfH:bnfp4nl)_

**Comment by airabinovich** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[src/org/unc/lac/javapetriconcurrencymonitor/monitor/PetriMonitor.java, line 75 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/32#-KW5nWnlAvWxMkSfe62E:-KW5ty7ykRBBW_L1bMQ8:b-61x82z) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/f525cef93f05803b74e125a34bbe9354fc80d40a/src/org/unc/lac/javapetriconcurrencymonitor/monitor/PetriMonitor.java#L75)):_
<details><summary>

<i>Previously, mauriludemann (Mauri) wrote…</i></summary>



> Only question:
> This line don't create an AtomicBoolean array? why are you filling that array again with AtomicBooleans?
> </details>
> the array is created all filled with null

---

_[src/org/unc/lac/javapetriconcurrencymonitor/monitor/PetriMonitor.java, line 357 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/32#-KW5oBr1VH0B0Bj-5vIJ:-KW5uA5dZWzrXY30mTvw:bwdr74g) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/f525cef93f05803b74e125a34bbe9354fc80d40a/src/org/unc/lac/javapetriconcurrencymonitor/monitor/PetriMonitor.java#L357)):_
<details><summary>

<i>Previously, mauriludemann (Mauri) wrote…</i></summary>



> "releases" - "sleeps"
> </details>
> it's written in imperative

---

_[src/org/unc/lac/javapetriconcurrencymonitor/monitor/PetriMonitor.java, line 360 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/32#-KW5p1fZm_M5cTkoT4yr:-KW5uHF8ev0K-wteqaZx:b-benl8g) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/f525cef93f05803b74e125a34bbe9354fc80d40a/src/org/unc/lac/javapetriconcurrencymonitor/monitor/PetriMonitor.java#L360)):_
<details><summary>

<i>Previously, mauriludemann (Mauri) wrote…</i></summary>



> This part must move to PetriNet like Orlando said, i think it would be better to do that in other branch.
> </details>
> sure but that's not this review's objective. I'll do it when solving issue #31 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/32)_

**Comment by mauriludemann** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

_[src/org/unc/lac/javapetriconcurrencymonitor/monitor/PetriMonitor.java, line 75 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/32#-KW5nWnlAvWxMkSfe62E:-KW5upKh68Rh7vtYiNQN:buwjtg5) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/f525cef93f05803b74e125a34bbe9354fc80d40a/src/org/unc/lac/javapetriconcurrencymonitor/monitor/PetriMonitor.java#L75)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> the array is created all filled with null
> </details>
> And "new AtomicBoolean()"? false?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/32)_

**Review by mauriludemann — APPROVED** [review]

**Comment by airabinovich** [comment]
_[src/org/unc/lac/javapetriconcurrencymonitor/monitor/PetriMonitor.java, line 75 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/32#-KW5nWnlAvWxMkSfe62E:-KW86JlUTDXNm7Vy9Dg0:b-zhyk88) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/f525cef93f05803b74e125a34bbe9354fc80d40a/src/org/unc/lac/javapetriconcurrencymonitor/monitor/PetriMonitor.java#L75)):_
<details><summary>

<i>Previously, mauriludemann (Mauri) wrote…</i></summary>



> And "new AtomicBoolean()"? false?
> </details>
> Right, it's documented in java's api. Default constructor initializes with false

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/32)_

**Pull request merged**
