### PR TITLE
added the feature to get places by name

### PR DESCRIPTION
**Pull request by mauriludemann**
This change is [Reviewable](https://reviewable.io/reviews/airabinovich/java_petri_engine/37)

### CODE REVIEW

**Comment by airabinovich** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

_[src/org/unc/lac/javapetriconcurrencymonitor/petrinets/PetriNet.java, line 223 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/37#-KWgvQNJTdpTiM4NK_aY:-KWgvQNJTdpTiM4NK_aZ:b-duz9rp) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/3cf32cdfcc6f08f0cf18e5822b85a7a9c111c5e4/src/org/unc/lac/javapetriconcurrencymonitor/petrinets/PetriNet.java#L223)):_

> public Place getPlace(final String placeName){·

throws IllegalArgumentException missing

---

_[test/org/lac/javapetriconcurrencymonitor/test/cases/PetriNetTestSuite.java, line 820 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/37#-KWgwWy18BFDDgZWSh0s:-KWgwWy2QWWszkkKsGQ6:b-qvjhkp) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/3cf32cdfcc6f08f0cf18e5822b85a7a9c111c5e4/test/org/lac/javapetriconcurrencymonitor/test/cases/PetriNetTestSuite.java#L820)):_

> Then A copy of p4 

it's not a copy

---

_[test/org/lac/javapetriconcurrencymonitor/test/cases/PetriNetTestSuite.java, line 836 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/37#-KWgwckqvJHO-u53TeBw:-KWgwckqvJHO-u53TeBx:bojxkg0) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/3cf32cdfcc6f08f0cf18e5822b85a7a9c111c5e4/test/org/lac/javapetriconcurrencymonitor/test/cases/PetriNetTestSuite.java#L836)):_

> ``` Java
>       }
>   }
> }
> ```

add another test case where the requested place doesn't exist and check for IllegalArgumentException in catch clause

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/37)_

**Comment by mauriludemann** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

_[src/org/unc/lac/javapetriconcurrencymonitor/petrinets/PetriNet.java, line 223 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/37#-KWgvQNJTdpTiM4NK_aY:-KWjdssV642QVtHdEOd1:b-896fix) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/3cf32cdfcc6f08f0cf18e5822b85a7a9c111c5e4/src/org/unc/lac/javapetriconcurrencymonitor/petrinets/PetriNet.java#L223)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> > public Place getPlace(final String placeName){·
> 
> throws IllegalArgumentException missing
> </details>
> Done.

---

_[test/org/lac/javapetriconcurrencymonitor/test/cases/PetriNetTestSuite.java, line 820 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/37#-KWgwWy18BFDDgZWSh0s:-KWjeUc0OnvEsU9KStUQ:b8qems4) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/3cf32cdfcc6f08f0cf18e5822b85a7a9c111c5e4/test/org/lac/javapetriconcurrencymonitor/test/cases/PetriNetTestSuite.java#L820)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> > Then A copy of p4 
> 
> it's not a copy
> </details>
> Now, it is.

---

_[test/org/lac/javapetriconcurrencymonitor/test/cases/PetriNetTestSuite.java, line 836 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/37#-KWgwckqvJHO-u53TeBw:-KWjjBC_ydS40otWGkUA:b-896fix) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/3cf32cdfcc6f08f0cf18e5822b85a7a9c111c5e4/test/org/lac/javapetriconcurrencymonitor/test/cases/PetriNetTestSuite.java#L836)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> add another test case where the requested place doesn't exist and check for IllegalArgumentException in catch clause
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/37)_

**Comment by airabinovich** [comment]
Reviewed 1 of 2 files at r1.
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

_[test/org/lac/javapetriconcurrencymonitor/test/cases/PetriNetTestSuite.java, line 838 at r2](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/37#-KWjmHICxOkIioqqxiMf:-KWjmHICxOkIioqqxiMg:bkd9hdb) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/253402948663bba8be9ccf162d444701d9e6b6e0/test/org/lac/javapetriconcurrencymonitor/test/cases/PetriNetTestSuite.java#L838)):_

> A

article doesn't belong here

---

_[test/org/lac/javapetriconcurrencymonitor/test/cases/PetriNetTestSuite.java, line 848 at r2](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/37#-KWjm6sBVwV3r_5iXu67:-KWjm6sCewf-0TcKKD1t:b-yywq9h) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/253402948663bba8be9ccf162d444701d9e6b6e0/test/org/lac/javapetriconcurrencymonitor/test/cases/PetriNetTestSuite.java#L848)):_

> Assert.assertNotEquals(5, p4_aux.getMarking());·

this will never be reached, delete it

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/37)_

**Comment by mauriludemann** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

_[test/org/lac/javapetriconcurrencymonitor/test/cases/PetriNetTestSuite.java, line 838 at r2](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/37#-KWjmHICxOkIioqqxiMf:-KWjneGc0WqYyIR3XMFL:b-896fix) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/253402948663bba8be9ccf162d444701d9e6b6e0/test/org/lac/javapetriconcurrencymonitor/test/cases/PetriNetTestSuite.java#L838)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> > A
> 
> article doesn't belong here
> </details>
> Done.

---

_[test/org/lac/javapetriconcurrencymonitor/test/cases/PetriNetTestSuite.java, line 848 at r2](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/37#-KWjm6sBVwV3r_5iXu67:-KWjndVCOFGdTfgWJsPB:b-896fix) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/253402948663bba8be9ccf162d444701d9e6b6e0/test/org/lac/javapetriconcurrencymonitor/test/cases/PetriNetTestSuite.java#L848)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> > Assert.assertNotEquals(5, p4_aux.getMarking());·
> 
> this will never be reached, delete it
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/37)_

**Comment by airabinovich** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/37#-:-KWjrH1U7RVttF5oNVwZ:bnfp4nl)_

**Comment by airabinovich** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/37)_

**Review by airabinovich — APPROVED** [review]

**Pull request merged**
