### PR TITLE
Added logic for processing reader arcs

### PR DESCRIPTION
**Pull request by airabinovich**
as well as tests for the parsing and the fire logic.

The parsing was already implemented but now the matrix is built and the logic for firing with reader arcs was added.

---

This change is [Reviewable](https://reviewable.io/reviews/airabinovich/java_petri_engine/23)

### CODE REVIEW

**Comment by mauriludemann** [comment]
_[src/Petri/PTPetriNet.java, line 9 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/23#-KUPaFbUXvo8P2ccHZJE:-KUPaFbUXvo8P2ccHZJF:bq9tawi) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/939992fef535ee96ad67a029d31c453e8b199b67/src/Petri/PTPetriNet.java#L9)):_

> ``` Java
>    * @see PetriNet#PetriNet(Place[], Transition[], Arc[], Integer[], Integer[][], Integer[][], Integer[][])
>    */
>   public PTPetriNet(Place[] _places, Transition[] _transitions, Arc[] _arcs, Integer[] _initialMarking,
> ```

We have a constructor for:
- PetriNet with no special arcs
- PetriNet with inhibition and reset arcs
- PetriNet with inhibition, reset and reader arcs.

I think we need to fix that, different contructors for different type of arcs, or other solution.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/23)_

**Comment by mauriludemann** [comment]
_[src/Petri/TimedPetriNet.java, line 13 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/23#-KUPawZjzVBQSyJE6txz:-KUPawZjzVBQSyJE6ty-:b-ya81ng) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/939992fef535ee96ad67a029d31c453e8b199b67/src/Petri/TimedPetriNet.java#L13)):_

> ``` Java
>    * @see PetriNet#PetriNet(Place[], Transition[], Arc[], Integer[], Integer[][], Integer[][], Integer[][])
>    */
>   public TimedPetriNet(Place[] _places, Transition[] _transitions, Arc[] _arcs, Integer[] _initialMarking,
> ```

Same as above

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/23)_

**Comment by mauriludemann** [comment]
_[test/unit_tests/PNMLreaderTestSuite.java, line 469 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/23#-KUPc24XRP5kfpViHcg3:-KUPc24XRP5kfpViHcg4:b-e4xtqo) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/939992fef535ee96ad67a029d31c453e8b199b67/test/unit_tests/PNMLreaderTestSuite.java#L469)):_

> ``` Java
> 
>   /**
>    * <li> Given p2 feeds t2 with a read arc </li>
> ```

reader arc*

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/23)_

**Comment by mauriludemann** [comment]
We can add another case, testing if there is a reset or inhibitor arc, and a reder arc with the same target transition, the parser throws an error

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/23#-:-KUPcerwsugoTSgKRVhC:bj6ctvi)_

**Comment by juanjoarce7456** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

_[src/Petri/PTPetriNet.java, line 9 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/23#-KUPaFbUXvo8P2ccHZJE:-KUSTWyA1nWeLd0qW5gj:b-fi6kiv) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/939992fef535ee96ad67a029d31c453e8b199b67/src/Petri/PTPetriNet.java#L9)):_
<details><summary>

<i>Previously, mauriludemann (Mauri) wrote…</i></summary>



> We have a constructor for:
> - PetriNet with no special arcs
> - PetriNet with inhibition and reset arcs
> - PetriNet with inhibition, reset and reader arcs.
> 
> I think we need to fix that, different contructors for different type of arcs, or other solution.
> </details>
> If you want different constructors for every kind of petri this solution is just fine. But I was thinking maybe there are a lot of different constructors. What happens if the user just put null on the constructor parameters he don't want to use?. I know it's not clean, but the guy doesn't have to learn how to use 10 different constructors. Again, it's just an opinion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/23)_

**Comment by juanjoarce7456** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/23)_

**Comment by airabinovich** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[src/Petri/PTPetriNet.java, line 9 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/23#-KUPaFbUXvo8P2ccHZJE:-KUTLMdooMvIYCwGOWam:bxp89lv) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/939992fef535ee96ad67a029d31c453e8b199b67/src/Petri/PTPetriNet.java#L9)):_
<details><summary>

<i>Previously, juanjoarce7456 wrote…</i></summary>



> If you want different constructors for every kind of petri this solution is just fine. But I was thinking maybe there are a lot of different constructors. What happens if the user just put null on the constructor parameters he don't want to use?. I know it's not clean, but the guy doesn't have to learn how to use 10 different constructors. Again, it's just an opinion.
> </details>
> You're right, I'll simplify this

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/23)_

**Comment by airabinovich** [comment]
Review status: 4 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

_[src/Petri/TimedPetriNet.java, line 13 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/23#-KUPawZjzVBQSyJE6txz:-KUi35iTOznnyDKTgTzY:b-896fix) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/939992fef535ee96ad67a029d31c453e8b199b67/src/Petri/TimedPetriNet.java#L13)):_
<details><summary>

<i>Previously, mauriludemann (Mauri) wrote…</i></summary>



> Same as above
> </details>
> Done.

---

_[test/unit_tests/PNMLreaderTestSuite.java, line 469 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/23#-KUPc24XRP5kfpViHcg3:-KUi2tN4TMXh-8yDI520:b-896fix) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/939992fef535ee96ad67a029d31c453e8b199b67/test/unit_tests/PNMLreaderTestSuite.java#L469)):_
<details><summary>

<i>Previously, mauriludemann (Mauri) wrote…</i></summary>



> reader arc*
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/23)_

**Comment by juanjoarce7456** [comment]
:lgtm:

---

Review status: 4 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/23#-:-KUtEYMTxudmqQ6z_zj_:bnfp4nl)_

**Comment by juanjoarce7456** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/23)_

**Comment by mauriludemann** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/23#-:-KUtZveEmyrP2vOjPHm2:bnfp4nl)_

**Pull request merged**
