### PR TITLE
Fix issue #42

### PR DESCRIPTION
**Pull request by airabinovich**
Added a test for that case

---
This change is [Reviewable](https://reviewable.io/reviews/airabinovich/java_petri_engine/45)

### CODE REVIEW

**Comment by juanjoarce7456** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/org/unc/lac/javapetriconcurrencymonitor/monitor/PetriMonitor.java, line 81 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/45#-KXlSSba56k5Esmm92Pt:-KXlSSbbaIM81Qp568O_:b-neimx3) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/2ac56049cac536cb75df15ee6d9122cca2c05484/src/org/unc/lac/javapetriconcurrencymonitor/monitor/PetriMonitor.java#L81)):*
> ```Java
> 			anyThreadSleepingforTransition[i] = new AtomicBoolean(false);
> 		}
> //		Arrays.fill(anyThreadSleepingforTransition, new AtomicBoolean());
> ```

Please remove the commented line. The problem was Arrays.fill filled the array with the same object reference and you need a new atomic boolean for every transition, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/45)*

**Comment by juanjoarce7456** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/org/unc/lac/javapetriconcurrencymonitor/monitor/PetriMonitor.java, line 81 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/45#-KXlSSba56k5Esmm92Pt:-KXnaxR_SBgEmQb8lffi:b32w0x) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/2ac56049cac536cb75df15ee6d9122cca2c05484/src/org/unc/lac/javapetriconcurrencymonitor/monitor/PetriMonitor.java#L81)):*
<details><summary><i>Previously, juanjoarce7456 (Juan Jose Arce Giacobbe) wrote…</i></summary><blockquote>

Please remove the commented line. The problem was Arrays.fill filled the array with the same object reference and you need a new atomic boolean for every transition, right?
</blockquote></details>

OK

---

*[test/org/lac/javapetriconcurrencymonitor/test/resources/timedPetri04.pnml, line 73 at r2](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/45#-KXnb9MCtn-4dpyQft3K:-KXnb9MCtn-4dpyQft3L:b-ljao01) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/6df40c8f94e8019c1f12ec01c01fb300c680dbbf/test/org/lac/javapetriconcurrencymonitor/test/resources/timedPetri04.pnml#L73)):*
> 200
Just asking: Is this interval in milliseconds or seconds?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/45)*

**Comment by juanjoarce7456** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/45#-:-KXnbpS0HMqiUy4ItEtO:bnfp4nl)*

**Comment by juanjoarce7456** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/45)*

**Comment by mauriludemann** [comment]
*[test/org/lac/javapetriconcurrencymonitor/test/resources/timedPetri04.pnml, line 73 at r2](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/45#-KXnb9MCtn-4dpyQft3K:-KXpNpblrAHauE9E7i0K:buah3tj) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/6df40c8f94e8019c1f12ec01c01fb300c680dbbf/test/org/lac/javapetriconcurrencymonitor/test/resources/timedPetri04.pnml#L73)):*
<details><summary><i>Previously, juanjoarce7456 (Juan Jose Arce Giacobbe) wrote…</i></summary><blockquote>

> 200
Just asking: Is this interval in milliseconds or seconds?
</blockquote></details>

milliseconds

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/45)*

**Comment by mauriludemann** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/45#-:-KXpOPwM7rDFQ2zzpT99:bnfp4nl)*

**Comment by mauriludemann** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/45)*

**Pull request merged**
