### PR TITLE
Add inhibitor arcs

### PR DESCRIPTION
**Pull request by airabinovich**
Logic for parsing and executing petri nets with inhibitor arcs

---

This change is [Reviewable](https://reviewable.io/reviews/airabinovich/java_petri_engine/9)

### CODE REVIEW

**Comment by airabinovich** [comment]
Not ready yet.
I'd like to add a few more tests, specially for firing from monitor.
Besides, I'd like to add some integrity checks (i.e. an inhibitor arc must not go from a transition to a place)

---

EDIT:
Previous mentioned lacking features and testing were added

**Comment by airabinovich** [comment]
_[src/Petri/Arc.java, line 75 at r2](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/9#-KSxrvZO_bIxnzEBuIGe:-KSxrvZO_bIxnzEBuIGf:b794lms) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/cfa1a72aff6649e6ce1a5048328555d5fbf55de1/src/Petri/Arc.java#L75)):_

> ``` Java
>           throw new IllegalArgumentException("Invalid null parameter recieved");
>       }
>       if(_weight < 1){
> ```

Take this comparison to a private method and check if type is inhibitor. In that case weight **must** be 1

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/9)_

**Comment by airabinovich** [comment]
_[src/Petri/Arc.java, line 75 at r2](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/9#-KSxrvZO_bIxnzEBuIGe:-KT5CNXNUW_fr2pRWUzY:b-896fix) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/cfa1a72aff6649e6ce1a5048328555d5fbf55de1/src/Petri/Arc.java#L75)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> Take this comparison to a private method and check if type is inhibitor. In that case weight **must** be 1
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/9)_

**Comment by mauriludemann** [comment]
_[src/Petri/PetriNet.java, line 55 at r3](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/9#-KTCZcIl8cSxV1cvrNQZ:-KTCZcImObgZcuqqHTbU:b4oymai) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/4ff89646fbc9c01479fc075bd0d8f6529a687d1f/src/Petri/PetriNet.java#L55)):_

> ``` Java
>    * @param _posI Post-Incidence matrix (dimension p*t)
>    * @param _I Incidence matrix (dimension p*t)
>    */
> ```

"@param _inhinitionMatrix" is absent in the javadoc

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/9)_

**Comment by mauriludemann** [comment]
_[src/Petri/PetriNet.java, line 230 at r3](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/9#-KTC_qFUiezZp9t4XQtV:-KTC_qFUiezZp9t4XQtW:b-uls076) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/4ff89646fbc9c01479fc075bd0d8f6529a687d1f/src/Petri/PetriNet.java#L230)):_

> ``` Java
>       for(int i=0; i<places.length ; i++){
>           if (pre[i][transitionIndex] > currentMarking[i]){
>               return false;
> ```

I don't like have multiple returns, this could be "enabled" variable returned at the end of method, and add the question "if(enabled)" before ask about guards and inhibitor arcs.
Just my point of view

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/9)_

**Comment by mauriludemann** [comment]
Reviewed 10 of 12 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/9)_

**Comment by airabinovich** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_[src/Petri/Arc.java, line 12 at r3](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/9#-KTFvschGYNVDa6fkNc6:-KTFvschGYNVDa6fkNc7:b-h55zsc) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/4ff89646fbc9c01479fc075bd0d8f6529a687d1f/src/Petri/Arc.java#L12)):_

> ``` Java
>        * Its weight is the amount of token drained from or given to a place
>        */
>       STANDARD,
> ```

this should be NORMAL

---

_[src/Petri/Arc.java, line 22 at r3](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/9#-KTFvwk3XeeDLaCXnRgr:-KTFvwk4zT6vY69t9zR-:b9ap01v) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/4ff89646fbc9c01479fc075bd0d8f6529a687d1f/src/Petri/Arc.java#L22)):_

> ``` Java
>        * in this type of arc the transition fire doesn't drain any tokens from the place
>        */
>       READER;
> ```

this should be READ

---

_[src/Petri/PetriNet.java, line 55 at r3](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/9#-KTCZcIl8cSxV1cvrNQZ:-KTFvjaJg5NtHdYB489s:b-2bakpp) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/4ff89646fbc9c01479fc075bd0d8f6529a687d1f/src/Petri/PetriNet.java#L55)):_
<details><summary>

<i>Previously, mauriludemann wrote…</i></summary>



> "@param _inhinitionMatrix" is absent in the javadoc
> </details>
> I'll add it in next review

---

_[src/Petri/PetriNet.java, line 230 at r3](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/9#-KTC_qFUiezZp9t4XQtV:-KTFvPeRGAEQUrkAWq8D:bun6hl7) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/4ff89646fbc9c01479fc075bd0d8f6529a687d1f/src/Petri/PetriNet.java#L230)):_
<details><summary>

<i>Previously, mauriludemann wrote…</i></summary>



> I don't like have multiple returns, this could be "enabled" variable returned at the end of method, and add the question "if(enabled)" before ask about guards and inhibitor arcs.
> Just my point of view
> </details>
> This way the loop is short-circuited without adding more logic, is to improve performance mostly. Besides adding logic to use a single return at the end would make the code less readable

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/9)_

**Comment by airabinovich** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

_[src/Petri/Arc.java, line 12 at r3](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/9#-KTFvschGYNVDa6fkNc6:-KTGxdeNzdgYjLJEXlhf:b-896fix) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/4ff89646fbc9c01479fc075bd0d8f6529a687d1f/src/Petri/Arc.java#L12)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> this should be NORMAL
> </details>
> Done.

---

_[src/Petri/Arc.java, line 22 at r3](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/9#-KTFvwk3XeeDLaCXnRgr:-KTGxjEQLXRM6kZ-g_BP:b-896fix) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/4ff89646fbc9c01479fc075bd0d8f6529a687d1f/src/Petri/Arc.java#L22)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> this should be READ
> </details>
> Done.

---

_[src/Petri/PetriNet.java, line 55 at r3](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/9#-KTCZcIl8cSxV1cvrNQZ:-KTGy4YkE7QGZL5oHLy-:b-896fix) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/4ff89646fbc9c01479fc075bd0d8f6529a687d1f/src/Petri/PetriNet.java#L55)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> I'll add it in next review
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/9)_

**Review by mauriludemann — APPROVED** [review]

**Comment by mauriludemann** [comment]
Reviewed 5 of 5 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/9)_

**Pull request merged**
