### PR TITLE
Refactor of petri net factory

### PR DESCRIPTION
**Pull request by airabinovich**
Simplification added to rdpObjects2Matrices. Since now places and transitions are ordered and know their indexes in the matrices, building the matrices can be simplified.
Besides, illegal petriNet topologies check responsibility was moved to PNMLreader where it should've been.

TODO: Add tests for illegal topologies

---

This change is [Reviewable](https://reviewable.io/reviews/airabinovich/java_petri_engine/15)

### CODE REVIEW

**Comment by airabinovich** [comment]
Reviewed 4 of 5 files at r1, 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[src/Petri/Arc.java, line 133 at r2](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/15#-KTQ5HamIPtuKJwLq7wX:-KTQ5HamIPtuKJwLq7wY:byst49k) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/7fbaebea3d61124f86cbef087277fd3e613709cd/src/Petri/Arc.java#L133)):_

> is

typo: if

---

_[src/Petri/PetriNetFactory.java, line 45 at r2](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/15#-KTQ3NHxKItRzBw3P1mU:-KTQ3NHyo-TPG7eoYeps:bjoau2a) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/7fbaebea3d61124f86cbef087277fd3e613709cd/src/Petri/PetriNetFactory.java#L45)):_

> @throws CannotCreatePetriNetError If the parsed info has inconsistent data.

update this doc with rdpObjects2Matrices' doc

---

_[src/Petri/PetriNetFactory.java, line 91 at r2](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/15#-KTQ1gtFOYn2pyazkTMB:-KTQ1gtGlXUlG0tTSWcq:bq8n5w9) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/7fbaebea3d61124f86cbef087277fd3e613709cd/src/Petri/PetriNetFactory.java#L91)):_

> rdpObjects2Matrices

this name got outdated in the translation process. Should be petriNetObjects2Matrices

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/15)_

**Comment by airabinovich** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_[src/Petri/PetriNetFactory.java, line 45 at r2](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/15#-KTQ3NHxKItRzBw3P1mU:-KTQ8TMJrGyslLKtVZHR:b-896fix) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/7fbaebea3d61124f86cbef087277fd3e613709cd/src/Petri/PetriNetFactory.java#L45)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> > @throws CannotCreatePetriNetError If the parsed info has inconsistent data.
> 
> update this doc with rdpObjects2Matrices' doc
> </details>
> Done.

---

_[src/Petri/PetriNetFactory.java, line 91 at r2](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/15#-KTQ1gtFOYn2pyazkTMB:-KTQ8fUfNfqanGntOG1H:b-896fix) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/7fbaebea3d61124f86cbef087277fd3e613709cd/src/Petri/PetriNetFactory.java#L91)):_
<details><summary>

<i>Previously, airabinovich (Ariel Iván Rabinovich) wrote…</i></summary>



> > rdpObjects2Matrices
> 
> this name got outdated in the translation process. Should be petriNetObjects2Matrices
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/15)_

**Comment by mauriludemann** [comment]
_[src/Petri/PetriNetFactory.java, line 71 at r3](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/15#-KTTzD0IfUa1-BIFaeqc:-KTTzD0IfUa1-BIFaeqd:b52hhvt) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/c635d3ff02808a9801ae86e95d09f5337d3cc3b0/src/Petri/PetriNetFactory.java#L71)):_

> ``` Java
>        * @throws CannotCreatePetriNetError If an error occurs during parsing
>        */
>       protected Quartet<Place[], Transition[], Arc[], Integer[]> PNML2PNObjects() throws CannotCreatePetriNetError{
> ```

PNML2Objects

Should be PNMLToObjects according to "petriNetObjects'To'Matrices"

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/15)_

**Comment by mauriludemann** [comment]
_[src/Petri/PetriNetFactory.java, line 73 at r3](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/15#-KTTztEAfVzUI_keR7VN:-KTTztEAfVzUI_keR7VO:b-tiz82p) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/c635d3ff02808a9801ae86e95d09f5337d3cc3b0/src/Petri/PetriNetFactory.java#L73)):_

> ``` Java
>       protected Quartet<Place[], Transition[], Arc[], Integer[]> PNML2PNObjects() throws CannotCreatePetriNetError{
>           try{
>               Triplet<Place[], Transition[], Arc[]> ret = reader.parseFileAndGetPetriObjects();
> ```

ret

Could have a better name

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/15)_

**Comment by mauriludemann** [comment]
_[src/Petri/PetriNetFactory.java, line 163 at r3](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/15#-KTU1_fLylNXKU24geam:-KTU1_fLylNXKU24gean:b5cxjtq) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/c635d3ff02808a9801ae86e95d09f5337d3cc3b0/src/Petri/PetriNetFactory.java#L163)):_

> ``` Java
>           }
> 
>           // now we have both matrixes pre and pos, let's get inc = pos - pre
> ```

The inc matrix could be calculated when pre and post matrices are filled.
if there is an arc goes from place to transition, fills the pre matrix, and also substract the arc weight from inc matrix
if there is an arc goes from transition to place, fills the post matrix, and algo plus the arc weight to inc matrix

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/15)_

**Comment by mauriludemann** [comment]
_[src/Petri/PNMLreader.java, line 272 at r3](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/15#-KTU49cdeEchoYR2TlzU:-KTU49cdeEchoYR2TlzV:b-5smop1) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/c635d3ff02808a9801ae86e95d09f5337d3cc3b0/src/Petri/PNMLreader.java#L272)):_

> ``` Java
>    * @param id the object id embedded in the PNML
>    * @param arcNode Node object from PNML
>    * @param nl arcNode children nodes as NodeList
> ```

@param places
@param transitions

Are absent in javadoc

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/15)_

**Comment by mauriludemann** [comment]
_[src/Petri/PNMLreader.java, line 314 at r3](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/15#-KTU6lcNk9N9Y7bQ0Gle:-KTU6lcO17pw2lQdzQwR:b-ncpufb) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/c635d3ff02808a9801ae86e95d09f5337d3cc3b0/src/Petri/PNMLreader.java#L314)):_

> ``` Java
>           throw new BadPNMLFormatException("Negative or zero weight found parsing arc");
>       }
> 
> ```

This could be enhanced, source and target both are PetriNodes, so you can make a function and don't duplicate this code.
Action is not required here

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/15)_

**Comment by mauriludemann** [comment]
Reviewed 2 of 5 files at r1, 8 of 8 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/15)_

**Comment by mauriludemann** [comment]
Reviewed 6 of 6 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/15)_

**Comment by airabinovich** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[src/Petri/PetriNetFactory.java, line 71 at r3](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/15#-KTTzD0IfUa1-BIFaeqc:-KTUJ8I3z8qaV95cT75L:b-3dyvze) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/c635d3ff02808a9801ae86e95d09f5337d3cc3b0/src/Petri/PetriNetFactory.java#L71)):_
<details><summary>

<i>Previously, mauriludemann wrote…</i></summary>



> PNML2Objects
> 
> Should be PNMLToObjects according to "petriNetObjects'To'Matrices"
> </details>
> Done.
> I adjusted the name to java naming conventions and to the javadoc description

---

_[src/Petri/PetriNetFactory.java, line 73 at r3](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/15#-KTTztEAfVzUI_keR7VN:-KTUEfxMuFHtmzbOruiT:by4l482) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/c635d3ff02808a9801ae86e95d09f5337d3cc3b0/src/Petri/PetriNetFactory.java#L73)):_
<details><summary>

<i>Previously, mauriludemann wrote…</i></summary>



> ret
> 
> Could have a better name
> </details>
> ret from return value, it's used just in these two lines. No need for a better name

---

_[src/Petri/PetriNetFactory.java, line 163 at r3](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/15#-KTU1_fLylNXKU24geam:-KTUSJc8TB4i3GZmSCId:b-896fix) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/c635d3ff02808a9801ae86e95d09f5337d3cc3b0/src/Petri/PetriNetFactory.java#L163)):_
<details><summary>

<i>Previously, mauriludemann wrote…</i></summary>



> The inc matrix could be calculated when pre and post matrices are filled.
> if there is an arc goes from place to transition, fills the pre matrix, and also substract the arc weight from inc matrix
> if there is an arc goes from transition to place, fills the post matrix, and algo plus the arc weight to inc matrix
> </details>
> Done.

---

_[src/Petri/PNMLreader.java, line 272 at r3](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/15#-KTU49cdeEchoYR2TlzU:-KTUJmitHdNRmoDopErD:b-896fix) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/c635d3ff02808a9801ae86e95d09f5337d3cc3b0/src/Petri/PNMLreader.java#L272)):_
<details><summary>

<i>Previously, mauriludemann wrote…</i></summary>



> @param places
> @param transitions
> 
> Are absent in javadoc
> </details>
> Done.

---

_[src/Petri/PNMLreader.java, line 314 at r3](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/15#-KTU6lcNk9N9Y7bQ0Gle:-KTUaV8tNEvknNz9SB_R:b-896fix) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/c635d3ff02808a9801ae86e95d09f5337d3cc3b0/src/Petri/PNMLreader.java#L314)):_
<details><summary>

<i>Previously, mauriludemann wrote…</i></summary>



> This could be enhanced, source and target both are PetriNodes, so you can make a function and don't duplicate this code.
> Action is not required here
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/15)_

**Pull request merged**
