### PR TITLE
Transition name fire and message and names and ids uniques

### PR DESCRIPTION
**Pull request by airabinovich**
Added transition name to informed fire message.
Added interface for firing using transition name.
Added checks for unique names and ids for transitions and places. If there are repeated, an error is thrown.
Added tests for all of the above.

---

This change is [Reviewable](https://reviewable.io/reviews/airabinovich/java_petri_engine/21)

### CODE REVIEW

**Comment by mauriludemann** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/21)_

**Comment by juanjoarce7456** [comment]
Reviewed 4 of 10 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/21)_

**Comment by juanjoarce7456** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/21#-:-KU0CVsY7CzHzDtM0fl4:bnfp4nl)_

**Review by mauriludemann — APPROVED** [review]

**Comment by mauriludemann** [comment]
:lgtm:

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/21#-:-KU0JqFJqzVmqtq0NpQz:bnfp4nl)_

**Comment by mauriludemann** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/21)_

**Pull request merged**
