### PR TITLE
Renamed packages, classes and methods to follow java naming convention.

### PR DESCRIPTION
**Pull request by airabinovich**
Also fixed javadoc and comments

This fixes to issue #2

---
This change is [Reviewable](https://reviewable.io/reviews/airabinovich/java_petri_engine/29)

### CODE REVIEW

**Comment by juanjoarce7456** [comment]
Reviewed 54 of 158 files at r1.
Review status: 27 of 79 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/org/lac/javapetriengine/engine/PetriEngine.java, line 1 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/29#-KVSXS7oA7UPZaRN1Gsm:-KVSXS7oA7UPZaRN1Gsn:brpj6qu) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/8bda82b499329bacd497ba559f4b4ffbdb03fd63/src/org/lac/javapetriengine/engine/PetriEngine.java#L1)):_

> org.lac.javapetriengine.engine
> I used org.unc.lac please choose one of the two options, either you change it or I change it.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/29)_

**Comment by juanjoarce7456** [comment]
Reviewed 104 of 158 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/29)_

**Comment by airabinovich** [comment]
_[src/org/lac/javapetriengine/engine/PetriEngine.java, line 1 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/29#-KVSXS7oA7UPZaRN1Gsm:-KVSdFA_d_GwMAaxuQEh:b-etp9z1) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/8bda82b499329bacd497ba559f4b4ffbdb03fd63/src/org/lac/javapetriengine/engine/PetriEngine.java#L1)):_
<details><summary>

<i>Previously, juanjoarce7456 wrote…</i></summary>



> > org.lac.javapetriengine.engine
> > I used org.unc.lac please choose one of the two options, either you change it or I change it.
> > </details>
> > let's use unc. It makes sense

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/29)_

**Comment by juanjoarce7456** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/29#-:-KVShQnTRyTLX45HukIA:bnfp4nl)_

**Comment by juanjoarce7456** [comment]
:lgtm:

---

Reviewed 79 of 237 files at r1, 158 of 158 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/29#-:-KVjZpQPFRwyTcQD3443:bnfp4nl)_

**Pull request merged**
