### PR TITLE
Convert to maven project

### PR DESCRIPTION
**Pull request by airabinovich**
* Removed all dependencies from lib directory
* Modified all test files to comply with maven for automatic run
* Fixed test resources paths to be loaded as resources

---
This change is [Reviewable](https://reviewable.io/reviews/airabinovich/java_petri_engine/60)

### CODE REVIEW

**Comment by juanjoarce7456** [comment]
Review status: 0 of 22 files reviewed at latest revision, 1 unresolved discussion.

---

*[lib/jackson-annotations-2.8.2-javadoc.jar, line 0 at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/60#-KwaK3cUvdhyAsniwX6N:-KwaK3cUvdhyAsniwX6O:b6g67ji) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/ec8c8c663e2f8a55b7a1782570235ca805cc7fc6/lib/jackson-annotations-2.8.2-javadoc.jar#L0)):*
Please add /lib directory to .gitignore

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/60)*

**Comment by juanjoarce7456** [comment]
Reviewed 30 of 30 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/60)*

**Comment by juanjoarce7456** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[lib/jackson-annotations-2.8.2-javadoc.jar, line  at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/60#-KwaK3cUvdhyAsniwX6N:-KwaL4jSJRX_7gtNADID:bm6caee) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/ec8c8c663e2f8a55b7a1782570235ca805cc7fc6/lib/jackson-annotations-2.8.2-javadoc.jar#L)):*
<details><summary><i>Previously, juanjoarce7456 (Juan Jose Arce Giacobbe) wrote…</i></summary><blockquote>

Please add /lib directory to .gitignore
</blockquote></details>

My bad, you are removing the files. LGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/60)*

**Comment by juanjoarce7456** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/60#-:-KwaLLIjSY7Hl4Z_i9Ny:bnfp4nl)*

**Comment by juanjoarce7456** [comment]
*[lib/jackson-annotations-2.8.2-javadoc.jar, line  at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/60#-KwaK3cUvdhyAsniwX6N:-KwaLPiaGFUwqJaEqMOu:b32w0x) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/ec8c8c663e2f8a55b7a1782570235ca805cc7fc6/lib/jackson-annotations-2.8.2-javadoc.jar#L)):*
<details><summary><i>Previously, juanjoarce7456 (Juan Jose Arce Giacobbe) wrote…</i></summary><blockquote>

My bad, you are removing the files. LGTM
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/60)*

**Comment by airabinovich** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[lib/jackson-annotations-2.8.2-javadoc.jar, line  at r1](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/60#-KwaK3cUvdhyAsniwX6N:-KwaMRyNz_ZC4YaHe9tV:b-896fix) ([raw file](https://github.com/airabinovich/java_petri_engine/blob/ec8c8c663e2f8a55b7a1782570235ca805cc7fc6/lib/jackson-annotations-2.8.2-javadoc.jar#L)):*
<details><summary><i>Previously, juanjoarce7456 (Juan Jose Arce Giacobbe) wrote…</i></summary><blockquote>

OK
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/airabinovich/java_petri_engine/60)*

**Pull request merged**
